/* Generated by Parser/pgen */

#include "grammar.h"
static const arc arcs_0_0[10] = {
    {2, 1},
    {3, 1},
    {4, 2},
    {5, 2},
    {6, 3},
    {7, 2},
    {8, 2},
    {9, 2},
    {10, 2},
    {11, 2},
};
static const arc arcs_0_1[1] = {
    {0, 1},
};
static const arc arcs_0_2[2] = {
    {2, 1},
    {3, 1},
};
static const arc arcs_0_3[9] = {
    {2, 1},
    {3, 1},
    {4, 2},
    {5, 2},
    {7, 2},
    {8, 2},
    {9, 2},
    {10, 2},
    {11, 2},
};
static state states_0[4] = {
    {10, arcs_0_0},
    {1, arcs_0_1},
    {2, arcs_0_2},
    {9, arcs_0_3},
};
static const arc arcs_1_0[2] = {
    {30, 1},
    {50, 1},
};
static const arc arcs_1_1[1] = {
    {59, 2},
};
static const arc arcs_1_2[1] = {
    {0, 2},
};
static state states_1[3] = {
    {2, arcs_1_0},
    {1, arcs_1_1},
    {1, arcs_1_2},
};
static const arc arcs_2_0[1] = {
    {53, 1},
};
static const arc arcs_2_1[3] = {
    {60, 2},
    {61, 2},
    {0, 1},
};
static const arc arcs_2_2[1] = {
    {0, 2},
};
static state states_2[3] = {
    {1, arcs_2_0},
    {3, arcs_2_1},
    {1, arcs_2_2},
};
static const arc arcs_3_0[2] = {
    {13, 1},
    {29, 1},
};
static const arc arcs_3_1[1] = {
    {62, 2},
};
static const arc arcs_3_2[1] = {
    {0, 2},
};
static state states_3[3] = {
    {2, arcs_3_0},
    {1, arcs_3_1},
    {1, arcs_3_2},
};
static const arc arcs_4_0[2] = {
    {27, 1},
    {54, 2},
};
static const arc arcs_4_1[1] = {
    {0, 1},
};
static const arc arcs_4_2[11] = {
    {63, 3},
    {64, 4},
    {65, 3},
    {66, 4},
    {67, 4},
    {68, 4},
    {69, 3},
    {70, 4},
    {71, 3},
    {62, 1},
    {0, 2},
};
static const arc arcs_4_3[2] = {
    {62, 1},
    {0, 3},
};
static const arc arcs_4_4[6] = {
    {63, 3},
    {65, 3},
    {69, 3},
    {71, 3},
    {62, 1},
    {0, 4},
};
static state states_4[5] = {
    {2, arcs_4_0},
    {1, arcs_4_1},
    {11, arcs_4_2},
    {2, arcs_4_3},
    {6, arcs_4_4},
};
static const arc arcs_5_0[3] = {
    {12, 1},
    {26, 2},
    {52, 2},
};
static const arc arcs_5_1[1] = {
    {53, 3},
};
static const arc arcs_5_2[1] = {
    {0, 2},
};
static const arc arcs_5_3[1] = {
    {72, 4},
};
static const arc arcs_5_4[2] = {
    {73, 3},
    {0, 4},
};
static state states_5[5] = {
    {3, arcs_5_0},
    {1, arcs_5_1},
    {1, arcs_5_2},
    {1, arcs_5_3},
    {2, arcs_5_4},
};
static const arc arcs_6_0[1] = {
    {51, 1},
};
static const arc arcs_6_1[1] = {
    {74, 2},
};
static const arc arcs_6_2[1] = {
    {0, 2},
};
static state states_6[3] = {
    {1, arcs_6_0},
    {1, arcs_6_1},
    {1, arcs_6_2},
};
static const arc arcs_7_0[16] = {
    {75, 1},
    {76, 1},
    {77, 1},
    {78, 1},
    {79, 1},
    {80, 1},
    {81, 1},
    {82, 1},
    {83, 1},
    {84, 1},
    {85, 1},
    {86, 1},
    {87, 1},
    {88, 1},
    {89, 1},
    {90, 1},
};
static const arc arcs_7_1[1] = {
    {0, 1},
};
static state states_7[2] = {
    {16, arcs_7_0},
    {1, arcs_7_1},
};
static const arc arcs_8_0[1] = {
    {38, 1},
};
static const arc arcs_8_1[6] = {
    {65, 2},
    {91, 2},
    {71, 2},
    {62, 3},
    {92, 4},
    {93, 4},
};
static const arc arcs_8_2[1] = {
    {62, 3},
};
static const arc arcs_8_3[2] = {
    {94, 4},
    {0, 3},
};
static const arc arcs_8_4[1] = {
    {0, 4},
};
static state states_8[5] = {
    {1, arcs_8_0},
    {6, arcs_8_1},
    {1, arcs_8_2},
    {2, arcs_8_3},
    {1, arcs_8_4},
};
static const arc arcs_9_0[1] = {
    {39, 1},
};
static const arc arcs_9_1[5] = {
    {95, 2},
    {65, 3},
    {71, 3},
    {62, 4},
    {0, 1},
};
static const arc arcs_9_2[1] = {
    {0, 2},
};
static const arc arcs_9_3[1] = {
    {62, 4},
};
static const arc arcs_9_4[2] = {
    {96, 2},
    {0, 4},
};
static state states_9[5] = {
    {1, arcs_9_0},
    {5, arcs_9_1},
    {1, arcs_9_2},
    {1, arcs_9_3},
    {2, arcs_9_4},
};
static const arc arcs_10_0[1] = {
    {40, 1},
};
static const arc arcs_10_1[4] = {
    {65, 2},
    {91, 2},
    {71, 2},
    {62, 3},
};
static const arc arcs_10_2[1] = {
    {62, 3},
};
static const arc arcs_10_3[1] = {
    {0, 3},
};
static state states_10[4] = {
    {1, arcs_10_0},
    {4, arcs_10_1},
    {1, arcs_10_2},
    {1, arcs_10_3},
};
static const arc arcs_11_0[1] = {
    {41, 1},
};
static const arc arcs_11_1[4] = {
    {65, 2},
    {71, 2},
    {62, 3},
    {92, 4},
};
static const arc arcs_11_2[1] = {
    {62, 3},
};
static const arc arcs_11_3[2] = {
    {96, 4},
    {0, 3},
};
static const arc arcs_11_4[1] = {
    {0, 4},
};
static state states_11[5] = {
    {1, arcs_11_0},
    {4, arcs_11_1},
    {1, arcs_11_2},
    {2, arcs_11_3},
    {1, arcs_11_4},
};
static const arc arcs_12_0[1] = {
    {42, 1},
};
static const arc arcs_12_1[4] = {
    {65, 2},
    {71, 2},
    {62, 3},
    {92, 3},
};
static const arc arcs_12_2[1] = {
    {62, 3},
};
static const arc arcs_12_3[1] = {
    {0, 3},
};
static state states_12[4] = {
    {1, arcs_12_0},
    {4, arcs_12_1},
    {1, arcs_12_2},
    {1, arcs_12_3},
};
static const arc arcs_13_0[1] = {
    {43, 1},
};
static const arc arcs_13_1[1] = {
    {92, 2},
};
static const arc arcs_13_2[1] = {
    {0, 2},
};
static state states_13[3] = {
    {1, arcs_13_0},
    {1, arcs_13_1},
    {1, arcs_13_2},
};
static const arc arcs_14_0[1] = {
    {44, 1},
};
static const arc arcs_14_1[1] = {
    {62, 2},
};
static const arc arcs_14_2[1] = {
    {73, 3},
};
static const arc arcs_14_3[1] = {
    {62, 4},
};
static const arc arcs_14_4[1] = {
    {0, 4},
};
static state states_14[5] = {
    {1, arcs_14_0},
    {1, arcs_14_1},
    {1, arcs_14_2},
    {1, arcs_14_3},
    {1, arcs_14_4},
};
static const arc arcs_15_0[1] = {
    {45, 1},
};
static const arc arcs_15_1[3] = {
    {91, 2},
    {62, 3},
    {97, 3},
};
static const arc arcs_15_2[1] = {
    {62, 3},
};
static const arc arcs_15_3[1] = {
    {0, 3},
};
static state states_15[4] = {
    {1, arcs_15_0},
    {3, arcs_15_1},
    {1, arcs_15_2},
    {1, arcs_15_3},
};
static const arc arcs_16_0[1] = {
    {46, 1},
};
static const arc arcs_16_1[3] = {
    {91, 2},
    {62, 3},
    {97, 3},
};
static const arc arcs_16_2[1] = {
    {62, 3},
};
static const arc arcs_16_3[1] = {
    {0, 3},
};
static state states_16[4] = {
    {1, arcs_16_0},
    {3, arcs_16_1},
    {1, arcs_16_2},
    {1, arcs_16_3},
};
static const arc arcs_17_0[1] = {
    {31, 1},
};
static const arc arcs_17_1[2] = {
    {91, 2},
    {62, 3},
};
static const arc arcs_17_2[1] = {
    {62, 3},
};
static const arc arcs_17_3[1] = {
    {0, 3},
};
static state states_17[4] = {
    {1, arcs_17_0},
    {2, arcs_17_1},
    {1, arcs_17_2},
    {1, arcs_17_3},
};
static const arc arcs_18_0[1] = {
    {32, 1},
};
static const arc arcs_18_1[4] = {
    {65, 2},
    {71, 2},
    {62, 3},
    {92, 4},
};
static const arc arcs_18_2[1] = {
    {62, 3},
};
static const arc arcs_18_3[2] = {
    {98, 4},
    {0, 3},
};
static const arc arcs_18_4[1] = {
    {0, 4},
};
static state states_18[5] = {
    {1, arcs_18_0},
    {4, arcs_18_1},
    {1, arcs_18_2},
    {2, arcs_18_3},
    {1, arcs_18_4},
};
static const arc arcs_19_0[1] = {
    {33, 1},
};
static const arc arcs_19_1[3] = {
    {65, 2},
    {71, 2},
    {62, 3},
};
static const arc arcs_19_2[1] = {
    {62, 3},
};
static const arc arcs_19_3[2] = {
    {98, 4},
    {0, 3},
};
static const arc arcs_19_4[1] = {
    {0, 4},
};
static state states_19[5] = {
    {1, arcs_19_0},
    {3, arcs_19_1},
    {1, arcs_19_2},
    {2, arcs_19_3},
    {1, arcs_19_4},
};
static const arc arcs_20_0[1] = {
    {34, 1},
};
static const arc arcs_20_1[3] = {
    {65, 2},
    {71, 2},
    {62, 3},
};
static const arc arcs_20_2[1] = {
    {62, 3},
};
static const arc arcs_20_3[2] = {
    {96, 4},
    {0, 3},
};
static const arc arcs_20_4[1] = {
    {0, 4},
};
static state states_20[5] = {
    {1, arcs_20_0},
    {3, arcs_20_1},
    {1, arcs_20_2},
    {2, arcs_20_3},
    {1, arcs_20_4},
};
static const arc arcs_21_0[1] = {
    {35, 1},
};
static const arc arcs_21_1[1] = {
    {0, 1},
};
static state states_21[2] = {
    {1, arcs_21_0},
    {1, arcs_21_1},
};
static const arc arcs_22_0[1] = {
    {36, 1},
};
static const arc arcs_22_1[1] = {
    {62, 2},
};
static const arc arcs_22_2[1] = {
    {0, 2},
};
static state states_22[3] = {
    {1, arcs_22_0},
    {1, arcs_22_1},
    {1, arcs_22_2},
};
static const arc arcs_23_0[1] = {
    {37, 1},
};
static const arc arcs_23_1[3] = {
    {99, 2},
    {62, 3},
    {0, 1},
};
static const arc arcs_23_2[1] = {
    {62, 3},
};
static const arc arcs_23_3[1] = {
    {0, 3},
};
static state states_23[4] = {
    {1, arcs_23_0},
    {3, arcs_23_1},
    {1, arcs_23_2},
    {1, arcs_23_3},
};
static const arc arcs_24_0[3] = {
    {99, 1},
    {100, 2},
    {101, 2},
};
static const arc arcs_24_1[1] = {
    {62, 3},
};
static const arc arcs_24_2[1] = {
    {99, 1},
};
static const arc arcs_24_3[1] = {
    {0, 3},
};
static state states_24[4] = {
    {3, arcs_24_0},
    {1, arcs_24_1},
    {1, arcs_24_2},
    {1, arcs_24_3},
};
static const arc arcs_25_0[1] = {
    {102, 1},
};
static const arc arcs_25_1[1] = {
    {62, 2},
};
static const arc arcs_25_2[1] = {
    {103, 3},
};
static const arc arcs_25_3[2] = {
    {98, 4},
    {0, 3},
};
static const arc arcs_25_4[1] = {
    {0, 4},
};
static state states_25[5] = {
    {1, arcs_25_0},
    {1, arcs_25_1},
    {1, arcs_25_2},
    {2, arcs_25_3},
    {1, arcs_25_4},
};
static const arc arcs_26_0[1] = {
    {102, 1},
};
static const arc arcs_26_1[1] = {
    {62, 2},
};
static const arc arcs_26_2[1] = {
    {103, 3},
};
static const arc arcs_26_3[1] = {
    {0, 3},
};
static state states_26[4] = {
    {1, arcs_26_0},
    {1, arcs_26_1},
    {1, arcs_26_2},
    {1, arcs_26_3},
};
static const arc arcs_27_0[1] = {
    {73, 1},
};
static const arc arcs_27_1[1] = {
    {104, 2},
};
static const arc arcs_27_2[1] = {
    {0, 2},
};
static state states_27[3] = {
    {1, arcs_27_0},
    {1, arcs_27_1},
    {1, arcs_27_2},
};
static const arc arcs_28_0[1] = {
    {73, 1},
};
static const arc arcs_28_1[1] = {
    {105, 2},
};
static const arc arcs_28_2[1] = {
    {0, 2},
};
static state states_28[3] = {
    {1, arcs_28_0},
    {1, arcs_28_1},
    {1, arcs_28_2},
};
static const arc arcs_29_0[1] = {
    {73, 1},
};
static const arc arcs_29_1[1] = {
    {107, 2},
};
static const arc arcs_29_2[1] = {
    {0, 2},
};
static state states_29[3] = {
    {1, arcs_29_0},
    {1, arcs_29_1},
    {1, arcs_29_2},
};
static const arc arcs_30_0[1] = {
    {73, 1},
};
static const arc arcs_30_1[2] = {
    {104, 2},
    {105, 2},
};
static const arc arcs_30_2[1] = {
    {0, 2},
};
static state states_30[3] = {
    {1, arcs_30_0},
    {2, arcs_30_1},
    {1, arcs_30_2},
};
static const arc arcs_31_0[1] = {
    {73, 1},
};
static const arc arcs_31_1[2] = {
    {107, 2},
    {104, 2},
};
static const arc arcs_31_2[1] = {
    {0, 2},
};
static state states_31[3] = {
    {1, arcs_31_0},
    {2, arcs_31_1},
    {1, arcs_31_2},
};
static const arc arcs_32_0[1] = {
    {73, 1},
};
static const arc arcs_32_1[2] = {
    {107, 2},
    {105, 2},
};
static const arc arcs_32_2[1] = {
    {0, 2},
};
static state states_32[3] = {
    {1, arcs_32_0},
    {2, arcs_32_1},
    {1, arcs_32_2},
};
static const arc arcs_33_0[1] = {
    {73, 1},
};
static const arc arcs_33_1[3] = {
    {107, 2},
    {104, 2},
    {105, 2},
};
static const arc arcs_33_2[1] = {
    {0, 2},
};
static state states_33[3] = {
    {1, arcs_33_0},
    {3, arcs_33_1},
    {1, arcs_33_2},
};
static const arc arcs_34_0[2] = {
    {12, 1},
    {53, 2},
};
static const arc arcs_34_1[1] = {
    {53, 3},
};
static const arc arcs_34_2[4] = {
    {112, 3},
    {12, 4},
    {60, 3},
    {0, 2},
};
static const arc arcs_34_3[1] = {
    {0, 3},
};
static const arc arcs_34_4[2] = {
    {53, 3},
    {0, 4},
};
static state states_34[5] = {
    {2, arcs_34_0},
    {1, arcs_34_1},
    {4, arcs_34_2},
    {1, arcs_34_3},
    {2, arcs_34_4},
};
static const arc arcs_35_0[2] = {
    {12, 1},
    {53, 2},
};
static const arc arcs_35_1[2] = {
    {53, 3},
    {0, 1},
};
static const arc arcs_35_2[2] = {
    {12, 1},
    {0, 2},
};
static const arc arcs_35_3[1] = {
    {0, 3},
};
static state states_35[4] = {
    {2, arcs_35_0},
    {2, arcs_35_1},
    {2, arcs_35_2},
    {1, arcs_35_3},
};
static const arc arcs_36_0[1] = {
    {113, 1},
};
static const arc arcs_36_1[2] = {
    {114, 0},
    {0, 1},
};
static state states_36[2] = {
    {1, arcs_36_0},
    {2, arcs_36_1},
};
static const arc arcs_37_0[1] = {
    {126, 1},
};
static const arc arcs_37_1[2] = {
    {127, 0},
    {0, 1},
};
static state states_37[2] = {
    {1, arcs_37_0},
    {2, arcs_37_1},
};
static const arc arcs_38_0[2] = {
    {115, 1},
    {128, 2},
};
static const arc arcs_38_1[1] = {
    {126, 2},
};
static const arc arcs_38_2[1] = {
    {0, 2},
};
static state states_38[3] = {
    {2, arcs_38_0},
    {1, arcs_38_1},
    {1, arcs_38_2},
};
static const arc arcs_39_0[1] = {
    {129, 1},
};
static const arc arcs_39_1[2] = {
    {130, 0},
    {0, 1},
};
static state states_39[2] = {
    {1, arcs_39_0},
    {2, arcs_39_1},
};
static const arc arcs_40_0[6] = {
    {131, 1},
    {120, 1},
    {132, 1},
    {133, 1},
    {122, 1},
    {134, 1},
};
static const arc arcs_40_1[1] = {
    {0, 1},
};
static state states_40[2] = {
    {6, arcs_40_0},
    {1, arcs_40_1},
};
static const arc arcs_41_0[1] = {
    {135, 1},
};
static const arc arcs_41_1[2] = {
    {136, 0},
    {0, 1},
};
static state states_41[2] = {
    {1, arcs_41_0},
    {2, arcs_41_1},
};
static const arc arcs_42_0[1] = {
    {137, 1},
};
static const arc arcs_42_1[2] = {
    {138, 0},
    {0, 1},
};
static state states_42[2] = {
    {1, arcs_42_0},
    {2, arcs_42_1},
};
static const arc arcs_43_0[1] = {
    {139, 1},
};
static const arc arcs_43_1[2] = {
    {112, 0},
    {0, 1},
};
static state states_43[2] = {
    {1, arcs_43_0},
    {2, arcs_43_1},
};
static const arc arcs_44_0[1] = {
    {140, 1},
};
static const arc arcs_44_1[3] = {
    {121, 0},
    {123, 0},
    {0, 1},
};
static state states_44[2] = {
    {1, arcs_44_0},
    {3, arcs_44_1},
};
static const arc arcs_45_0[1] = {
    {141, 1},
};
static const arc arcs_45_1[3] = {
    {118, 0},
    {119, 0},
    {0, 1},
};
static state states_45[2] = {
    {1, arcs_45_0},
    {3, arcs_45_1},
};
static const arc arcs_46_0[1] = {
    {142, 1},
};
static const arc arcs_46_1[4] = {
    {143, 0},
    {117, 0},
    {144, 0},
    {0, 1},
};
static state states_46[2] = {
    {1, arcs_46_0},
    {4, arcs_46_1},
};
static const arc arcs_47_0[8] = {
    {118, 1},
    {119, 1},
    {120, 1},
    {121, 1},
    {122, 1},
    {123, 1},
    {124, 1},
    {145, 2},
};
static const arc arcs_47_1[1] = {
    {142, 2},
};
static const arc arcs_47_2[1] = {
    {0, 2},
};
static state states_47[3] = {
    {8, arcs_47_0},
    {1, arcs_47_1},
    {1, arcs_47_2},
};
static const arc arcs_48_0[5] = {
    {116, 1},
    {117, 2},
    {125, 2},
    {74, 2},
    {111, 2},
};
static const arc arcs_48_1[1] = {
    {62, 3},
};
static const arc arcs_48_2[1] = {
    {0, 2},
};
static const arc arcs_48_3[2] = {
    {146, 2},
    {109, 4},
};
static const arc arcs_48_4[1] = {
    {146, 2},
};
static state states_48[5] = {
    {5, arcs_48_0},
    {1, arcs_48_1},
    {1, arcs_48_2},
    {2, arcs_48_3},
    {1, arcs_48_4},
};
static const arc arcs_49_0[17] = {
    {16, 1},
    {17, 1},
    {18, 1},
    {24, 1},
    {25, 1},
    {28, 1},
    {55, 1},
    {56, 1},
    {57, 1},
    {58, 1},
    {147, 1},
    {148, 1},
    {149, 1},
    {150, 1},
    {151, 1},
    {152, 1},
    {153, 1},
};
static const arc arcs_49_1[1] = {
    {0, 1},
};
static state states_49[2] = {
    {17, arcs_49_0},
    {1, arcs_49_1},
};
static const arc arcs_50_0[1] = {
    {20, 1},
};
static const arc arcs_50_1[1] = {
    {62, 2},
};
static const arc arcs_50_2[2] = {
    {73, 1},
    {0, 2},
};
static state states_50[3] = {
    {1, arcs_50_0},
    {1, arcs_50_1},
    {2, arcs_50_2},
};
static const arc arcs_51_0[3] = {
    {19, 1},
    {21, 1},
    {23, 1},
};
static const arc arcs_51_1[1] = {
    {62, 2},
};
static const arc arcs_51_2[2] = {
    {73, 1},
    {0, 2},
};
static state states_51[3] = {
    {3, arcs_51_0},
    {1, arcs_51_1},
    {2, arcs_51_2},
};
static const arc arcs_52_0[1] = {
    {22, 1},
};
static const arc arcs_52_1[1] = {
    {62, 2},
};
static const arc arcs_52_2[1] = {
    {0, 2},
};
static state states_52[3] = {
    {1, arcs_52_0},
    {1, arcs_52_1},
    {1, arcs_52_2},
};
static const arc arcs_53_0[1] = {
    {14, 1},
};
static const arc arcs_53_1[5] = {
    {64, 2},
    {66, 2},
    {67, 2},
    {68, 2},
    {70, 2},
};
static const arc arcs_53_2[1] = {
    {0, 2},
};
static state states_53[3] = {
    {1, arcs_53_0},
    {5, arcs_53_1},
    {1, arcs_53_2},
};
static const arc arcs_54_0[1] = {
    {15, 1},
};
static const arc arcs_54_1[1] = {
    {62, 2},
};
static const arc arcs_54_2[1] = {
    {0, 2},
};
static state states_54[3] = {
    {1, arcs_54_0},
    {1, arcs_54_1},
    {1, arcs_54_2},
};
static const arc arcs_55_0[2] = {
    {48, 1},
    {49, 1},
};
static const arc arcs_55_1[1] = {
    {111, 2},
};
static const arc arcs_55_2[1] = {
    {0, 2},
};
static state states_55[3] = {
    {2, arcs_55_0},
    {1, arcs_55_1},
    {1, arcs_55_2},
};
static const arc arcs_56_0[1] = {
    {47, 1},
};
static const arc arcs_56_1[1] = {
    {62, 2},
};
static const arc arcs_56_2[1] = {
    {0, 2},
};
static state states_56[3] = {
    {1, arcs_56_0},
    {1, arcs_56_1},
    {1, arcs_56_2},
};
static const dfa dfas[57] = {
    {256, "line", 4, states_0,
     "\014\360\377\377\377\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000"},
    {257, "external", 3, states_1,
     "\000\000\000\100\000\000\004\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {258, "label", 3, states_2,
     "\000\000\000\000\000\000\040\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {259, "variable", 3, states_3,
     "\000\040\000\040\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {260, "region", 5, states_4,
     "\000\000\000\010\000\000\100\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {261, "macro", 5, states_5,
     "\000\020\000\004\000\000\020\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {262, "include", 3, states_6,
     "\000\000\000\000\000\000\010\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {263, "op_code", 2, states_7,
     "\000\000\000\200\377\177\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {264, "group1", 5, states_8,
     "\000\000\000\000\100\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {265, "group2", 5, states_9,
     "\000\000\000\000\200\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {266, "group3", 4, states_10,
     "\000\000\000\000\000\001\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {267, "group4", 5, states_11,
     "\000\000\000\000\000\002\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {268, "group5", 4, states_12,
     "\000\000\000\000\000\004\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {269, "group6", 3, states_13,
     "\000\000\000\000\000\010\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {270, "group7", 5, states_14,
     "\000\000\000\000\000\020\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {271, "group8", 4, states_15,
     "\000\000\000\000\000\040\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {272, "group9", 4, states_16,
     "\000\000\000\000\000\100\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {273, "group10", 4, states_17,
     "\000\000\000\200\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {274, "group11", 5, states_18,
     "\000\000\000\000\001\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {275, "group12", 5, states_19,
     "\000\000\000\000\002\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {276, "group13", 5, states_20,
     "\000\000\000\000\004\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {277, "group14", 2, states_21,
     "\000\000\000\000\010\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {278, "group15", 3, states_22,
     "\000\000\000\000\020\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {279, "group16", 4, states_23,
     "\000\000\000\000\040\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {280, "imm_exp", 4, states_24,
     "\000\000\000\000\000\000\000\000\000\000\000\000\070\000\000\000\000\000\000\000"},
    {281, "long_ind_exp", 5, states_25,
     "\000\000\000\000\000\000\000\000\000\000\000\000\100\000\000\000\000\000\000\000"},
    {282, "jmp_long_ind_exp", 4, states_26,
     "\000\000\000\000\000\000\000\000\000\000\000\000\100\000\000\000\000\000\000\000"},
    {283, "x_index", 3, states_27,
     "\000\000\000\000\000\000\000\000\000\002\000\000\000\000\000\000\000\000\000\000"},
    {284, "y_index", 3, states_28,
     "\000\000\000\000\000\000\000\000\000\002\000\000\000\000\000\000\000\000\000\000"},
    {285, "s_index", 3, states_29,
     "\000\000\000\000\000\000\000\000\000\002\000\000\000\000\000\000\000\000\000\000"},
    {286, "xy_index", 3, states_30,
     "\000\000\000\000\000\000\000\000\000\002\000\000\000\000\000\000\000\000\000\000"},
    {287, "xs_index", 3, states_31,
     "\000\000\000\000\000\000\000\000\000\002\000\000\000\000\000\000\000\000\000\000"},
    {288, "ys_index", 3, states_32,
     "\000\000\000\000\000\000\000\000\000\002\000\000\000\000\000\000\000\000\000\000"},
    {289, "xys_index", 3, states_33,
     "\000\000\000\000\000\000\000\000\000\002\000\000\000\000\000\000\000\000\000\000"},
    {290, "symbol", 5, states_34,
     "\000\020\000\000\000\000\040\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {291, "extern_addr", 4, states_35,
     "\000\020\000\000\000\000\040\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {292, "expr", 2, states_36,
     "\000\020\000\000\000\000\040\000\000\004\000\000\000\000\370\077\000\000\000\000"},
    {293, "and_cond", 2, states_37,
     "\000\020\000\000\000\000\040\000\000\004\000\000\000\000\370\077\000\000\000\000"},
    {294, "not_cond", 3, states_38,
     "\000\020\000\000\000\000\040\000\000\004\000\000\000\000\370\077\000\000\000\000"},
    {295, "comparison", 2, states_39,
     "\000\020\000\000\000\000\040\000\000\004\000\000\000\000\360\077\000\000\000\000"},
    {296, "comp_op", 2, states_40,
     "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\005\170\000\000\000"},
    {297, "or_exp", 2, states_41,
     "\000\020\000\000\000\000\040\000\000\004\000\000\000\000\360\077\000\000\000\000"},
    {298, "xor_expr", 2, states_42,
     "\000\020\000\000\000\000\040\000\000\004\000\000\000\000\360\077\000\000\000\000"},
    {299, "and_expr", 2, states_43,
     "\000\020\000\000\000\000\040\000\000\004\000\000\000\000\360\077\000\000\000\000"},
    {300, "shift_expr", 2, states_44,
     "\000\020\000\000\000\000\040\000\000\004\000\000\000\000\360\077\000\000\000\000"},
    {301, "arith_expr", 2, states_45,
     "\000\020\000\000\000\000\040\000\000\004\000\000\000\000\360\077\000\000\000\000"},
    {302, "term", 2, states_46,
     "\000\020\000\000\000\000\040\000\000\004\000\000\000\000\360\077\000\000\000\000"},
    {303, "factor", 3, states_47,
     "\000\020\000\000\000\000\040\000\000\004\000\000\000\000\360\077\000\000\000\000"},
    {304, "atom", 5, states_48,
     "\000\020\000\000\000\000\040\000\000\004\000\000\000\000\060\040\000\000\000\000"},
    {305, "pseudo_op", 2, states_49,
     "\000\300\377\023\000\200\203\007\000\000\000\000\000\000\000\000\000\000\000\000"},
    {306, "define_byte", 3, states_50,
     "\000\000\020\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {307, "define_word", 3, states_51,
     "\000\000\250\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {308, "define_storage", 3, states_52,
     "\000\000\100\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {309, "align", 3, states_53,
     "\000\100\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {310, "block", 3, states_54,
     "\000\200\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {311, "if_def", 3, states_55,
     "\000\000\000\000\000\000\003\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {312, "iff", 3, states_56,
     "\000\000\000\000\000\200\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
};
static const label labels[154] = {
    {0, "EMPTY"},
    {256, nullptr},
    {0, nullptr},
    {4, nullptr},
    {257, nullptr},
    {262, nullptr},
    {258, nullptr},
    {261, nullptr},
    {263, nullptr},
    {305, nullptr},
    {260, nullptr},
    {259, nullptr},
    {84, nullptr},
    {83, nullptr},
    {61, nullptr},
    {62, nullptr},
    {46, nullptr},
    {47, nullptr},
    {48, nullptr},
    {59, nullptr},
    {56, nullptr},
    {58, nullptr},
    {60, nullptr},
    {57, nullptr},
    {54, nullptr},
    {55, nullptr},
    {17, nullptr},
    {14, nullptr},
    {53, nullptr},
    {5, nullptr},
    {20, nullptr},
    {30, nullptr},
    {31, nullptr},
    {32, nullptr},
    {33, nullptr},
    {34, nullptr},
    {35, nullptr},
    {36, nullptr},
    {21, nullptr},
    {22, nullptr},
    {23, nullptr},
    {24, nullptr},
    {25, nullptr},
    {26, nullptr},
    {27, nullptr},
    {28, nullptr},
    {29, nullptr},
    {65, nullptr},
    {63, nullptr},
    {64, nullptr},
    {19, nullptr},
    {18, nullptr},
    {16, nullptr},
    {1, nullptr},
    {13, nullptr},
    {50, nullptr},
    {52, nullptr},
    {49, nullptr},
    {51, nullptr},
    {291, nullptr},
    {72, nullptr},
    {66, nullptr},
    {292, nullptr},
    {11, nullptr},
    {6, nullptr},
    {40, nullptr},
    {8, nullptr},
    {10, nullptr},
    {9, nullptr},
    {12, nullptr},
    {7, nullptr},
    {41, nullptr},
    {15, nullptr},
    {73, nullptr},
    {3, nullptr},
    {264, nullptr},
    {273, nullptr},
    {274, nullptr},
    {275, nullptr},
    {276, nullptr},
    {277, nullptr},
    {278, nullptr},
    {279, nullptr},
    {265, nullptr},
    {266, nullptr},
    {267, nullptr},
    {268, nullptr},
    {269, nullptr},
    {270, nullptr},
    {271, nullptr},
    {272, nullptr},
    {39, nullptr},
    {280, nullptr},
    {281, nullptr},
    {289, nullptr},
    {42, nullptr},
    {283, nullptr},
    {282, nullptr},
    {284, nullptr},
    {67, nullptr},
    {38, nullptr},
    {37, nullptr},
    {70, nullptr},
    {71, nullptr},
    {43, nullptr},
    {44, nullptr},
    {285, nullptr},
    {45, nullptr},
    {286, nullptr},
    {287, nullptr},
    {288, nullptr},
    {290, nullptr},
    {80, nullptr},
    {293, nullptr},
    {97, nullptr},
    {88, nullptr},
    {68, nullptr},
    {77, nullptr},
    {75, nullptr},
    {76, nullptr},
    {81, nullptr},
    {95, nullptr},
    {82, nullptr},
    {96, nullptr},
    {93, nullptr},
    {2, nullptr},
    {294, nullptr},
    {98, nullptr},
    {295, nullptr},
    {297, nullptr},
    {296, nullptr},
    {90, nullptr},
    {91, nullptr},
    {89, nullptr},
    {92, nullptr},
    {298, nullptr},
    {79, nullptr},
    {299, nullptr},
    {94, nullptr},
    {300, nullptr},
    {301, nullptr},
    {302, nullptr},
    {303, nullptr},
    {85, nullptr},
    {78, nullptr},
    {304, nullptr},
    {69, nullptr},
    {309, nullptr},
    {310, nullptr},
    {306, nullptr},
    {308, nullptr},
    {307, nullptr},
    {311, nullptr},
    {312, nullptr},
};
grammar casmGrammar = {
    57,
    dfas,
    {154, labels},
    256
};
