/* Generated by Parser/pgen */

#include "grammar.h"
static const arc arcs_0_0[8] = {
    {2, 1},
    {3, 1},
    {4, 2},
    {5, 3},
    {6, 3},
    {7, 3},
    {8, 3},
    {9, 3},
};
static const arc arcs_0_1[1] = {
    {0, 1},
};
static const arc arcs_0_2[7] = {
    {2, 1},
    {3, 1},
    {5, 3},
    {6, 3},
    {7, 3},
    {8, 3},
    {9, 3},
};
static const arc arcs_0_3[2] = {
    {2, 1},
    {3, 1},
};
static state states_0[4] = {
    {8, arcs_0_0},
    {1, arcs_0_1},
    {7, arcs_0_2},
    {2, arcs_0_3},
};
static const arc arcs_1_0[1] = {
    {48, 1},
};
static const arc arcs_1_1[3] = {
    {54, 2},
    {55, 2},
    {0, 1},
};
static const arc arcs_1_2[1] = {
    {0, 2},
};
static state states_1[3] = {
    {1, arcs_1_0},
    {3, arcs_1_1},
    {1, arcs_1_2},
};
static const arc arcs_2_0[2] = {
    {11, 1},
    {27, 1},
};
static const arc arcs_2_1[1] = {
    {56, 2},
};
static const arc arcs_2_2[1] = {
    {0, 2},
};
static state states_2[3] = {
    {2, arcs_2_0},
    {1, arcs_2_1},
    {1, arcs_2_2},
};
static const arc arcs_3_0[2] = {
    {25, 1},
    {49, 2},
};
static const arc arcs_3_1[1] = {
    {0, 1},
};
static const arc arcs_3_2[4] = {
    {57, 1},
    {58, 1},
    {56, 1},
    {0, 2},
};
static state states_3[3] = {
    {2, arcs_3_0},
    {1, arcs_3_1},
    {4, arcs_3_2},
};
static const arc arcs_4_0[3] = {
    {10, 1},
    {24, 2},
    {47, 3},
};
static const arc arcs_4_1[1] = {
    {48, 4},
};
static const arc arcs_4_2[1] = {
    {0, 2},
};
static const arc arcs_4_3[2] = {
    {48, 3},
    {0, 3},
};
static const arc arcs_4_4[1] = {
    {59, 5},
};
static const arc arcs_4_5[2] = {
    {60, 4},
    {0, 5},
};
static state states_4[6] = {
    {3, arcs_4_0},
    {1, arcs_4_1},
    {1, arcs_4_2},
    {2, arcs_4_3},
    {1, arcs_4_4},
    {2, arcs_4_5},
};
static const arc arcs_5_0[16] = {
    {61, 1},
    {62, 1},
    {63, 1},
    {64, 1},
    {65, 1},
    {66, 1},
    {67, 1},
    {68, 1},
    {69, 1},
    {70, 1},
    {71, 1},
    {72, 1},
    {73, 1},
    {74, 1},
    {75, 1},
    {76, 1},
};
static const arc arcs_5_1[1] = {
    {0, 1},
};
static state states_5[2] = {
    {16, arcs_5_0},
    {1, arcs_5_1},
};
static const arc arcs_6_0[1] = {
    {35, 1},
};
static const arc arcs_6_1[9] = {
    {77, 2},
    {78, 2},
    {79, 3},
    {80, 3},
    {81, 2},
    {82, 4},
    {83, 4},
    {84, 4},
    {85, 5},
};
static const arc arcs_6_2[1] = {
    {85, 5},
};
static const arc arcs_6_3[1] = {
    {82, 4},
};
static const arc arcs_6_4[1] = {
    {0, 4},
};
static const arc arcs_6_5[2] = {
    {86, 4},
    {0, 5},
};
static state states_6[6] = {
    {1, arcs_6_0},
    {9, arcs_6_1},
    {1, arcs_6_2},
    {1, arcs_6_3},
    {1, arcs_6_4},
    {2, arcs_6_5},
};
static const arc arcs_7_0[1] = {
    {36, 1},
};
static const arc arcs_7_1[3] = {
    {87, 2},
    {56, 3},
    {0, 1},
};
static const arc arcs_7_2[1] = {
    {0, 2},
};
static const arc arcs_7_3[2] = {
    {88, 2},
    {0, 3},
};
static state states_7[4] = {
    {1, arcs_7_0},
    {3, arcs_7_1},
    {1, arcs_7_2},
    {2, arcs_7_3},
};
static const arc arcs_8_0[1] = {
    {37, 1},
};
static const arc arcs_8_1[1] = {
    {56, 2},
};
static const arc arcs_8_2[1] = {
    {0, 2},
};
static state states_8[3] = {
    {1, arcs_8_0},
    {1, arcs_8_1},
    {1, arcs_8_2},
};
static const arc arcs_9_0[1] = {
    {38, 1},
};
static const arc arcs_9_1[4] = {
    {79, 2},
    {80, 2},
    {56, 3},
    {82, 4},
};
static const arc arcs_9_2[1] = {
    {82, 4},
};
static const arc arcs_9_3[2] = {
    {88, 4},
    {0, 3},
};
static const arc arcs_9_4[1] = {
    {0, 4},
};
static state states_9[5] = {
    {1, arcs_9_0},
    {4, arcs_9_1},
    {1, arcs_9_2},
    {2, arcs_9_3},
    {1, arcs_9_4},
};
static const arc arcs_10_0[1] = {
    {39, 1},
};
static const arc arcs_10_1[2] = {
    {56, 2},
    {82, 2},
};
static const arc arcs_10_2[1] = {
    {0, 2},
};
static state states_10[3] = {
    {1, arcs_10_0},
    {2, arcs_10_1},
    {1, arcs_10_2},
};
static const arc arcs_11_0[1] = {
    {40, 1},
};
static const arc arcs_11_1[3] = {
    {79, 2},
    {80, 2},
    {82, 3},
};
static const arc arcs_11_2[1] = {
    {82, 3},
};
static const arc arcs_11_3[1] = {
    {0, 3},
};
static state states_11[4] = {
    {1, arcs_11_0},
    {3, arcs_11_1},
    {1, arcs_11_2},
    {1, arcs_11_3},
};
static const arc arcs_12_0[1] = {
    {41, 1},
};
static const arc arcs_12_1[1] = {
    {56, 2},
};
static const arc arcs_12_2[1] = {
    {60, 3},
};
static const arc arcs_12_3[1] = {
    {56, 4},
};
static const arc arcs_12_4[1] = {
    {0, 4},
};
static state states_12[5] = {
    {1, arcs_12_0},
    {1, arcs_12_1},
    {1, arcs_12_2},
    {1, arcs_12_3},
    {1, arcs_12_4},
};
static const arc arcs_13_0[1] = {
    {42, 1},
};
static const arc arcs_13_1[4] = {
    {78, 2},
    {89, 3},
    {90, 3},
    {85, 3},
};
static const arc arcs_13_2[1] = {
    {85, 3},
};
static const arc arcs_13_3[1] = {
    {0, 3},
};
static state states_13[4] = {
    {1, arcs_13_0},
    {4, arcs_13_1},
    {1, arcs_13_2},
    {1, arcs_13_3},
};
static const arc arcs_14_0[1] = {
    {43, 1},
};
static const arc arcs_14_1[3] = {
    {78, 2},
    {56, 3},
    {90, 3},
};
static const arc arcs_14_2[1] = {
    {56, 3},
};
static const arc arcs_14_3[1] = {
    {0, 3},
};
static state states_14[4] = {
    {1, arcs_14_0},
    {3, arcs_14_1},
    {1, arcs_14_2},
    {1, arcs_14_3},
};
static const arc arcs_15_0[1] = {
    {28, 1},
};
static const arc arcs_15_1[3] = {
    {78, 2},
    {89, 3},
    {85, 3},
};
static const arc arcs_15_2[1] = {
    {85, 3},
};
static const arc arcs_15_3[1] = {
    {0, 3},
};
static state states_15[4] = {
    {1, arcs_15_0},
    {3, arcs_15_1},
    {1, arcs_15_2},
    {1, arcs_15_3},
};
static const arc arcs_16_0[1] = {
    {29, 1},
};
static const arc arcs_16_1[4] = {
    {79, 2},
    {80, 2},
    {56, 3},
    {82, 4},
};
static const arc arcs_16_2[1] = {
    {82, 4},
};
static const arc arcs_16_3[2] = {
    {91, 4},
    {0, 3},
};
static const arc arcs_16_4[1] = {
    {0, 4},
};
static state states_16[5] = {
    {1, arcs_16_0},
    {4, arcs_16_1},
    {1, arcs_16_2},
    {2, arcs_16_3},
    {1, arcs_16_4},
};
static const arc arcs_17_0[1] = {
    {30, 1},
};
static const arc arcs_17_1[1] = {
    {56, 2},
};
static const arc arcs_17_2[2] = {
    {91, 3},
    {0, 2},
};
static const arc arcs_17_3[1] = {
    {0, 3},
};
static state states_17[4] = {
    {1, arcs_17_0},
    {1, arcs_17_1},
    {2, arcs_17_2},
    {1, arcs_17_3},
};
static const arc arcs_18_0[1] = {
    {31, 1},
};
static const arc arcs_18_1[1] = {
    {56, 2},
};
static const arc arcs_18_2[2] = {
    {88, 3},
    {0, 2},
};
static const arc arcs_18_3[1] = {
    {0, 3},
};
static state states_18[4] = {
    {1, arcs_18_0},
    {1, arcs_18_1},
    {2, arcs_18_2},
    {1, arcs_18_3},
};
static const arc arcs_19_0[1] = {
    {32, 1},
};
static const arc arcs_19_1[1] = {
    {0, 1},
};
static state states_19[2] = {
    {1, arcs_19_0},
    {1, arcs_19_1},
};
static const arc arcs_20_0[1] = {
    {33, 1},
};
static const arc arcs_20_1[1] = {
    {92, 2},
};
static const arc arcs_20_2[1] = {
    {56, 3},
};
static const arc arcs_20_3[1] = {
    {93, 4},
};
static const arc arcs_20_4[1] = {
    {0, 4},
};
static state states_20[5] = {
    {1, arcs_20_0},
    {1, arcs_20_1},
    {1, arcs_20_2},
    {1, arcs_20_3},
    {1, arcs_20_4},
};
static const arc arcs_21_0[1] = {
    {34, 1},
};
static const arc arcs_21_1[4] = {
    {79, 2},
    {80, 2},
    {82, 3},
    {0, 1},
};
static const arc arcs_21_2[1] = {
    {82, 3},
};
static const arc arcs_21_3[1] = {
    {0, 3},
};
static state states_21[4] = {
    {1, arcs_21_0},
    {4, arcs_21_1},
    {1, arcs_21_2},
    {1, arcs_21_3},
};
static const arc arcs_22_0[1] = {
    {94, 1},
};
static const arc arcs_22_1[1] = {
    {56, 2},
};
static const arc arcs_22_2[1] = {
    {0, 2},
};
static state states_22[3] = {
    {1, arcs_22_0},
    {1, arcs_22_1},
    {1, arcs_22_2},
};
static const arc arcs_23_0[1] = {
    {95, 1},
};
static const arc arcs_23_1[1] = {
    {56, 2},
};
static const arc arcs_23_2[1] = {
    {96, 3},
};
static const arc arcs_23_3[2] = {
    {91, 4},
    {0, 3},
};
static const arc arcs_23_4[1] = {
    {0, 4},
};
static state states_23[5] = {
    {1, arcs_23_0},
    {1, arcs_23_1},
    {1, arcs_23_2},
    {2, arcs_23_3},
    {1, arcs_23_4},
};
static const arc arcs_24_0[1] = {
    {95, 1},
};
static const arc arcs_24_1[1] = {
    {56, 2},
};
static const arc arcs_24_2[1] = {
    {96, 3},
};
static const arc arcs_24_3[1] = {
    {0, 3},
};
static state states_24[4] = {
    {1, arcs_24_0},
    {1, arcs_24_1},
    {1, arcs_24_2},
    {1, arcs_24_3},
};
static const arc arcs_25_0[1] = {
    {92, 1},
};
static const arc arcs_25_1[1] = {
    {56, 2},
};
static const arc arcs_25_2[3] = {
    {93, 3},
    {97, 4},
    {88, 5},
};
static const arc arcs_25_3[3] = {
    {98, 6},
    {91, 6},
    {0, 3},
};
static const arc arcs_25_4[1] = {
    {93, 7},
};
static const arc arcs_25_5[1] = {
    {93, 6},
};
static const arc arcs_25_6[1] = {
    {0, 6},
};
static const arc arcs_25_7[1] = {
    {91, 6},
};
static state states_25[8] = {
    {1, arcs_25_0},
    {1, arcs_25_1},
    {3, arcs_25_2},
    {3, arcs_25_3},
    {1, arcs_25_4},
    {1, arcs_25_5},
    {1, arcs_25_6},
    {1, arcs_25_7},
};
static const arc arcs_26_0[1] = {
    {92, 1},
};
static const arc arcs_26_1[1] = {
    {56, 2},
};
static const arc arcs_26_2[2] = {
    {93, 3},
    {88, 4},
};
static const arc arcs_26_3[2] = {
    {99, 5},
    {0, 3},
};
static const arc arcs_26_4[1] = {
    {93, 5},
};
static const arc arcs_26_5[1] = {
    {0, 5},
};
static state states_26[6] = {
    {1, arcs_26_0},
    {1, arcs_26_1},
    {2, arcs_26_2},
    {2, arcs_26_3},
    {1, arcs_26_4},
    {1, arcs_26_5},
};
static const arc arcs_27_0[13] = {
    {100, 1},
    {101, 2},
    {102, 3},
    {103, 1},
    {104, 4},
    {105, 4},
    {106, 1},
    {107, 5},
    {108, 5},
    {109, 6},
    {110, 7},
    {111, 8},
    {112, 9},
};
static const arc arcs_27_1[1] = {
    {113, 10},
};
static const arc arcs_27_2[1] = {
    {114, 11},
};
static const arc arcs_27_3[1] = {
    {115, 12},
};
static const arc arcs_27_4[1] = {
    {116, 13},
};
static const arc arcs_27_5[1] = {
    {117, 14},
};
static const arc arcs_27_6[1] = {
    {118, 15},
};
static const arc arcs_27_7[1] = {
    {119, 16},
};
static const arc arcs_27_8[1] = {
    {120, 17},
};
static const arc arcs_27_9[1] = {
    {121, 18},
};
static const arc arcs_27_10[1] = {
    {122, 19},
};
static const arc arcs_27_11[1] = {
    {123, 19},
};
static const arc arcs_27_12[1] = {
    {124, 19},
};
static const arc arcs_27_13[1] = {
    {125, 19},
};
static const arc arcs_27_14[1] = {
    {126, 19},
};
static const arc arcs_27_15[1] = {
    {127, 19},
};
static const arc arcs_27_16[1] = {
    {128, 19},
};
static const arc arcs_27_17[1] = {
    {129, 19},
};
static const arc arcs_27_18[1] = {
    {130, 19},
};
static const arc arcs_27_19[2] = {
    {86, 20},
    {0, 19},
};
static const arc arcs_27_20[1] = {
    {0, 20},
};
static state states_27[21] = {
    {13, arcs_27_0},
    {1, arcs_27_1},
    {1, arcs_27_2},
    {1, arcs_27_3},
    {1, arcs_27_4},
    {1, arcs_27_5},
    {1, arcs_27_6},
    {1, arcs_27_7},
    {1, arcs_27_8},
    {1, arcs_27_9},
    {1, arcs_27_10},
    {1, arcs_27_11},
    {1, arcs_27_12},
    {1, arcs_27_13},
    {1, arcs_27_14},
    {1, arcs_27_15},
    {1, arcs_27_16},
    {1, arcs_27_17},
    {1, arcs_27_18},
    {2, arcs_27_19},
    {1, arcs_27_20},
};
static const arc arcs_28_0[13] = {
    {100, 1},
    {101, 2},
    {102, 3},
    {103, 1},
    {104, 4},
    {105, 4},
    {106, 1},
    {107, 5},
    {108, 5},
    {109, 6},
    {110, 7},
    {111, 8},
    {112, 9},
};
static const arc arcs_28_1[1] = {
    {113, 10},
};
static const arc arcs_28_2[1] = {
    {114, 11},
};
static const arc arcs_28_3[1] = {
    {115, 12},
};
static const arc arcs_28_4[1] = {
    {116, 13},
};
static const arc arcs_28_5[1] = {
    {117, 14},
};
static const arc arcs_28_6[1] = {
    {118, 15},
};
static const arc arcs_28_7[1] = {
    {119, 16},
};
static const arc arcs_28_8[1] = {
    {120, 17},
};
static const arc arcs_28_9[1] = {
    {121, 18},
};
static const arc arcs_28_10[1] = {
    {122, 19},
};
static const arc arcs_28_11[1] = {
    {123, 19},
};
static const arc arcs_28_12[1] = {
    {124, 19},
};
static const arc arcs_28_13[1] = {
    {125, 19},
};
static const arc arcs_28_14[1] = {
    {126, 19},
};
static const arc arcs_28_15[1] = {
    {127, 19},
};
static const arc arcs_28_16[1] = {
    {128, 19},
};
static const arc arcs_28_17[1] = {
    {129, 19},
};
static const arc arcs_28_18[1] = {
    {130, 19},
};
static const arc arcs_28_19[1] = {
    {0, 19},
};
static state states_28[20] = {
    {13, arcs_28_0},
    {1, arcs_28_1},
    {1, arcs_28_2},
    {1, arcs_28_3},
    {1, arcs_28_4},
    {1, arcs_28_5},
    {1, arcs_28_6},
    {1, arcs_28_7},
    {1, arcs_28_8},
    {1, arcs_28_9},
    {1, arcs_28_10},
    {1, arcs_28_11},
    {1, arcs_28_12},
    {1, arcs_28_13},
    {1, arcs_28_14},
    {1, arcs_28_15},
    {1, arcs_28_16},
    {1, arcs_28_17},
    {1, arcs_28_18},
    {1, arcs_28_19},
};
static const arc arcs_29_0[4] = {
    {100, 1},
    {103, 0},
    {106, 0},
    {125, 2},
};
static const arc arcs_29_1[1] = {
    {113, 0},
};
static const arc arcs_29_2[1] = {
    {0, 2},
};
static state states_29[3] = {
    {4, arcs_29_0},
    {1, arcs_29_1},
    {1, arcs_29_2},
};
static const arc arcs_30_0[3] = {
    {104, 1},
    {105, 1},
    {126, 2},
};
static const arc arcs_30_1[1] = {
    {116, 0},
};
static const arc arcs_30_2[1] = {
    {0, 2},
};
static state states_30[3] = {
    {3, arcs_30_0},
    {1, arcs_30_1},
    {1, arcs_30_2},
};
static const arc arcs_31_0[3] = {
    {107, 1},
    {108, 1},
    {124, 2},
};
static const arc arcs_31_1[1] = {
    {117, 0},
};
static const arc arcs_31_2[1] = {
    {0, 2},
};
static state states_31[3] = {
    {3, arcs_31_0},
    {1, arcs_31_1},
    {1, arcs_31_2},
};
static const arc arcs_32_0[2] = {
    {102, 1},
    {127, 2},
};
static const arc arcs_32_1[1] = {
    {115, 0},
};
static const arc arcs_32_2[1] = {
    {0, 2},
};
static state states_32[3] = {
    {2, arcs_32_0},
    {1, arcs_32_1},
    {1, arcs_32_2},
};
static const arc arcs_33_0[2] = {
    {109, 1},
    {128, 2},
};
static const arc arcs_33_1[1] = {
    {118, 0},
};
static const arc arcs_33_2[1] = {
    {0, 2},
};
static state states_33[3] = {
    {2, arcs_33_0},
    {1, arcs_33_1},
    {1, arcs_33_2},
};
static const arc arcs_34_0[2] = {
    {110, 1},
    {130, 2},
};
static const arc arcs_34_1[1] = {
    {119, 0},
};
static const arc arcs_34_2[1] = {
    {0, 2},
};
static state states_34[3] = {
    {2, arcs_34_0},
    {1, arcs_34_1},
    {1, arcs_34_2},
};
static const arc arcs_35_0[2] = {
    {112, 1},
    {123, 2},
};
static const arc arcs_35_1[1] = {
    {121, 0},
};
static const arc arcs_35_2[1] = {
    {0, 2},
};
static state states_35[3] = {
    {2, arcs_35_0},
    {1, arcs_35_1},
    {1, arcs_35_2},
};
static const arc arcs_36_0[2] = {
    {101, 1},
    {129, 2},
};
static const arc arcs_36_1[1] = {
    {114, 0},
};
static const arc arcs_36_2[1] = {
    {0, 2},
};
static state states_36[3] = {
    {2, arcs_36_0},
    {1, arcs_36_1},
    {1, arcs_36_2},
};
static const arc arcs_37_0[2] = {
    {111, 1},
    {0, 0},
};
static const arc arcs_37_1[1] = {
    {120, 0},
};
static state states_37[2] = {
    {2, arcs_37_0},
    {1, arcs_37_1},
};
static const arc arcs_38_0[1] = {
    {60, 1},
};
static const arc arcs_38_1[1] = {
    {137, 2},
};
static const arc arcs_38_2[1] = {
    {0, 2},
};
static state states_38[3] = {
    {1, arcs_38_0},
    {1, arcs_38_1},
    {1, arcs_38_2},
};
static const arc arcs_39_0[1] = {
    {60, 1},
};
static const arc arcs_39_1[1] = {
    {138, 2},
};
static const arc arcs_39_2[1] = {
    {0, 2},
};
static state states_39[3] = {
    {1, arcs_39_0},
    {1, arcs_39_1},
    {1, arcs_39_2},
};
static const arc arcs_40_0[1] = {
    {60, 1},
};
static const arc arcs_40_1[1] = {
    {139, 2},
};
static const arc arcs_40_2[1] = {
    {0, 2},
};
static state states_40[3] = {
    {1, arcs_40_0},
    {1, arcs_40_1},
    {1, arcs_40_2},
};
static const arc arcs_41_0[1] = {
    {60, 1},
};
static const arc arcs_41_1[2] = {
    {137, 2},
    {138, 2},
};
static const arc arcs_41_2[1] = {
    {0, 2},
};
static state states_41[3] = {
    {1, arcs_41_0},
    {2, arcs_41_1},
    {1, arcs_41_2},
};
static const arc arcs_42_0[1] = {
    {60, 1},
};
static const arc arcs_42_1[2] = {
    {139, 2},
    {137, 2},
};
static const arc arcs_42_2[1] = {
    {0, 2},
};
static state states_42[3] = {
    {1, arcs_42_0},
    {2, arcs_42_1},
    {1, arcs_42_2},
};
static const arc arcs_43_0[1] = {
    {60, 1},
};
static const arc arcs_43_1[2] = {
    {139, 2},
    {138, 2},
};
static const arc arcs_43_2[1] = {
    {0, 2},
};
static state states_43[3] = {
    {1, arcs_43_0},
    {2, arcs_43_1},
    {1, arcs_43_2},
};
static const arc arcs_44_0[1] = {
    {60, 1},
};
static const arc arcs_44_1[3] = {
    {139, 2},
    {137, 2},
    {138, 2},
};
static const arc arcs_44_2[1] = {
    {0, 2},
};
static state states_44[3] = {
    {1, arcs_44_0},
    {3, arcs_44_1},
    {1, arcs_44_2},
};
static const arc arcs_45_0[2] = {
    {10, 1},
    {48, 2},
};
static const arc arcs_45_1[1] = {
    {48, 3},
};
static const arc arcs_45_2[4] = {
    {102, 3},
    {10, 4},
    {54, 3},
    {0, 2},
};
static const arc arcs_45_3[1] = {
    {0, 3},
};
static const arc arcs_45_4[2] = {
    {48, 3},
    {0, 4},
};
static state states_45[5] = {
    {2, arcs_45_0},
    {1, arcs_45_1},
    {4, arcs_45_2},
    {1, arcs_45_3},
    {2, arcs_45_4},
};
static const arc arcs_46_0[1] = {
    {120, 1},
};
static const arc arcs_46_1[2] = {
    {111, 0},
    {0, 1},
};
static state states_46[2] = {
    {1, arcs_46_0},
    {2, arcs_46_1},
};
static const arc arcs_47_0[1] = {
    {114, 1},
};
static const arc arcs_47_1[2] = {
    {101, 0},
    {0, 1},
};
static state states_47[2] = {
    {1, arcs_47_0},
    {2, arcs_47_1},
};
static const arc arcs_48_0[2] = {
    {144, 1},
    {148, 2},
};
static const arc arcs_48_1[1] = {
    {114, 2},
};
static const arc arcs_48_2[1] = {
    {0, 2},
};
static state states_48[3] = {
    {2, arcs_48_0},
    {1, arcs_48_1},
    {1, arcs_48_2},
};
static const arc arcs_49_0[1] = {
    {121, 1},
};
static const arc arcs_49_1[2] = {
    {112, 0},
    {0, 1},
};
static state states_49[2] = {
    {1, arcs_49_0},
    {2, arcs_49_1},
};
static const arc arcs_50_0[6] = {
    {131, 1},
    {132, 1},
    {133, 1},
    {134, 1},
    {135, 1},
    {136, 1},
};
static const arc arcs_50_1[1] = {
    {0, 1},
};
static state states_50[2] = {
    {6, arcs_50_0},
    {1, arcs_50_1},
};
static const arc arcs_51_0[1] = {
    {119, 1},
};
static const arc arcs_51_1[2] = {
    {110, 0},
    {0, 1},
};
static state states_51[2] = {
    {1, arcs_51_0},
    {2, arcs_51_1},
};
static const arc arcs_52_0[1] = {
    {118, 1},
};
static const arc arcs_52_1[2] = {
    {109, 0},
    {0, 1},
};
static state states_52[2] = {
    {1, arcs_52_0},
    {2, arcs_52_1},
};
static const arc arcs_53_0[1] = {
    {115, 1},
};
static const arc arcs_53_1[2] = {
    {102, 0},
    {0, 1},
};
static state states_53[2] = {
    {1, arcs_53_0},
    {2, arcs_53_1},
};
static const arc arcs_54_0[1] = {
    {117, 1},
};
static const arc arcs_54_1[3] = {
    {107, 0},
    {108, 0},
    {0, 1},
};
static state states_54[2] = {
    {1, arcs_54_0},
    {3, arcs_54_1},
};
static const arc arcs_55_0[1] = {
    {116, 1},
};
static const arc arcs_55_1[3] = {
    {104, 0},
    {105, 0},
    {0, 1},
};
static state states_55[2] = {
    {1, arcs_55_0},
    {3, arcs_55_1},
};
static const arc arcs_56_0[1] = {
    {113, 1},
};
static const arc arcs_56_1[4] = {
    {100, 0},
    {103, 0},
    {106, 0},
    {0, 1},
};
static state states_56[2] = {
    {1, arcs_56_0},
    {4, arcs_56_1},
};
static const arc arcs_57_0[8] = {
    {104, 1},
    {105, 1},
    {132, 1},
    {107, 1},
    {135, 1},
    {108, 1},
    {145, 1},
    {149, 2},
};
static const arc arcs_57_1[1] = {
    {113, 2},
};
static const arc arcs_57_2[1] = {
    {0, 2},
};
static state states_57[3] = {
    {8, arcs_57_0},
    {1, arcs_57_1},
    {1, arcs_57_2},
};
static const arc arcs_58_0[5] = {
    {92, 1},
    {103, 2},
    {146, 2},
    {147, 2},
    {143, 2},
};
static const arc arcs_58_1[1] = {
    {56, 3},
};
static const arc arcs_58_2[1] = {
    {0, 2},
};
static const arc arcs_58_3[1] = {
    {93, 2},
};
static state states_58[4] = {
    {5, arcs_58_0},
    {1, arcs_58_1},
    {1, arcs_58_2},
    {1, arcs_58_3},
};
static const arc arcs_59_0[1] = {
    {150, 1},
};
static const arc arcs_59_1[2] = {
    {111, 2},
    {0, 1},
};
static const arc arcs_59_2[1] = {
    {120, 1},
};
static state states_59[3] = {
    {1, arcs_59_0},
    {2, arcs_59_1},
    {1, arcs_59_2},
};
static const arc arcs_60_0[1] = {
    {151, 1},
};
static const arc arcs_60_1[2] = {
    {101, 2},
    {0, 1},
};
static const arc arcs_60_2[1] = {
    {114, 1},
};
static state states_60[3] = {
    {1, arcs_60_0},
    {2, arcs_60_1},
    {1, arcs_60_2},
};
static const arc arcs_61_0[2] = {
    {144, 1},
    {152, 2},
};
static const arc arcs_61_1[1] = {
    {114, 2},
};
static const arc arcs_61_2[1] = {
    {0, 2},
};
static state states_61[3] = {
    {2, arcs_61_0},
    {1, arcs_61_1},
    {1, arcs_61_2},
};
static const arc arcs_62_0[1] = {
    {153, 1},
};
static const arc arcs_62_1[2] = {
    {112, 2},
    {0, 1},
};
static const arc arcs_62_2[1] = {
    {121, 1},
};
static state states_62[3] = {
    {1, arcs_62_0},
    {2, arcs_62_1},
    {1, arcs_62_2},
};
static const arc arcs_63_0[1] = {
    {154, 1},
};
static const arc arcs_63_1[2] = {
    {110, 2},
    {0, 1},
};
static const arc arcs_63_2[1] = {
    {119, 1},
};
static state states_63[3] = {
    {1, arcs_63_0},
    {2, arcs_63_1},
    {1, arcs_63_2},
};
static const arc arcs_64_0[1] = {
    {155, 1},
};
static const arc arcs_64_1[2] = {
    {109, 2},
    {0, 1},
};
static const arc arcs_64_2[1] = {
    {118, 1},
};
static state states_64[3] = {
    {1, arcs_64_0},
    {2, arcs_64_1},
    {1, arcs_64_2},
};
static const arc arcs_65_0[1] = {
    {156, 1},
};
static const arc arcs_65_1[2] = {
    {102, 2},
    {0, 1},
};
static const arc arcs_65_2[1] = {
    {115, 1},
};
static state states_65[3] = {
    {1, arcs_65_0},
    {2, arcs_65_1},
    {1, arcs_65_2},
};
static const arc arcs_66_0[1] = {
    {157, 1},
};
static const arc arcs_66_1[3] = {
    {107, 2},
    {108, 2},
    {0, 1},
};
static const arc arcs_66_2[1] = {
    {117, 1},
};
static state states_66[3] = {
    {1, arcs_66_0},
    {3, arcs_66_1},
    {1, arcs_66_2},
};
static const arc arcs_67_0[1] = {
    {158, 1},
};
static const arc arcs_67_1[3] = {
    {104, 2},
    {105, 2},
    {0, 1},
};
static const arc arcs_67_2[1] = {
    {116, 1},
};
static state states_67[3] = {
    {1, arcs_67_0},
    {3, arcs_67_1},
    {1, arcs_67_2},
};
static const arc arcs_68_0[1] = {
    {159, 1},
};
static const arc arcs_68_1[4] = {
    {100, 2},
    {103, 2},
    {106, 2},
    {0, 1},
};
static const arc arcs_68_2[1] = {
    {113, 1},
};
static state states_68[3] = {
    {1, arcs_68_0},
    {4, arcs_68_1},
    {1, arcs_68_2},
};
static const arc arcs_69_0[8] = {
    {104, 1},
    {105, 1},
    {132, 1},
    {107, 1},
    {135, 1},
    {108, 1},
    {145, 1},
    {160, 2},
};
static const arc arcs_69_1[1] = {
    {113, 2},
};
static const arc arcs_69_2[1] = {
    {0, 2},
};
static state states_69[3] = {
    {8, arcs_69_0},
    {1, arcs_69_1},
    {1, arcs_69_2},
};
static const arc arcs_70_0[4] = {
    {103, 1},
    {146, 1},
    {147, 1},
    {143, 1},
};
static const arc arcs_70_1[1] = {
    {0, 1},
};
static state states_70[2] = {
    {4, arcs_70_0},
    {1, arcs_70_1},
};
static const arc arcs_71_0[17] = {
    {14, 1},
    {15, 1},
    {16, 1},
    {22, 1},
    {23, 1},
    {26, 1},
    {50, 1},
    {51, 1},
    {52, 1},
    {53, 1},
    {161, 1},
    {162, 1},
    {163, 1},
    {164, 1},
    {165, 1},
    {166, 1},
    {167, 1},
};
static const arc arcs_71_1[1] = {
    {0, 1},
};
static state states_71[2] = {
    {17, arcs_71_0},
    {1, arcs_71_1},
};
static const arc arcs_72_0[1] = {
    {18, 1},
};
static const arc arcs_72_1[1] = {
    {56, 2},
};
static const arc arcs_72_2[2] = {
    {60, 1},
    {0, 2},
};
static state states_72[3] = {
    {1, arcs_72_0},
    {1, arcs_72_1},
    {2, arcs_72_2},
};
static const arc arcs_73_0[3] = {
    {17, 1},
    {19, 1},
    {21, 1},
};
static const arc arcs_73_1[1] = {
    {56, 2},
};
static const arc arcs_73_2[2] = {
    {60, 1},
    {0, 2},
};
static state states_73[3] = {
    {3, arcs_73_0},
    {1, arcs_73_1},
    {2, arcs_73_2},
};
static const arc arcs_74_0[1] = {
    {20, 1},
};
static const arc arcs_74_1[1] = {
    {56, 2},
};
static const arc arcs_74_2[1] = {
    {0, 2},
};
static state states_74[3] = {
    {1, arcs_74_0},
    {1, arcs_74_1},
    {1, arcs_74_2},
};
static const arc arcs_75_0[1] = {
    {12, 1},
};
static const arc arcs_75_1[2] = {
    {57, 2},
    {58, 2},
};
static const arc arcs_75_2[1] = {
    {0, 2},
};
static state states_75[3] = {
    {1, arcs_75_0},
    {2, arcs_75_1},
    {1, arcs_75_2},
};
static const arc arcs_76_0[1] = {
    {13, 1},
};
static const arc arcs_76_1[1] = {
    {56, 2},
};
static const arc arcs_76_2[1] = {
    {0, 2},
};
static state states_76[3] = {
    {1, arcs_76_0},
    {1, arcs_76_1},
    {1, arcs_76_2},
};
static const arc arcs_77_0[2] = {
    {45, 1},
    {46, 1},
};
static const arc arcs_77_1[1] = {
    {48, 2},
};
static const arc arcs_77_2[1] = {
    {0, 2},
};
static state states_77[3] = {
    {2, arcs_77_0},
    {1, arcs_77_1},
    {1, arcs_77_2},
};
static const arc arcs_78_0[1] = {
    {44, 1},
};
static const arc arcs_78_1[1] = {
    {56, 2},
};
static const arc arcs_78_2[1] = {
    {0, 2},
};
static state states_78[3] = {
    {1, arcs_78_0},
    {1, arcs_78_1},
    {1, arcs_78_2},
};
static const dfa dfas[79] = {
    {256, "line", 4, states_0,
     "\014\374\377\377\377\377\077\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {257, "label", 3, states_1,
     "\000\000\000\000\000\000\001\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {258, "variable", 3, states_2,
     "\000\010\000\010\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {259, "region", 3, states_3,
     "\000\000\000\002\000\000\002\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {260, "macro", 6, states_4,
     "\000\004\000\001\000\200\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {261, "op_code", 2, states_5,
     "\000\000\000\360\377\017\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {262, "group1", 6, states_6,
     "\000\000\000\000\010\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {263, "group2", 4, states_7,
     "\000\000\000\000\020\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {264, "group3", 3, states_8,
     "\000\000\000\000\040\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {265, "group4", 5, states_9,
     "\000\000\000\000\100\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {266, "group5", 3, states_10,
     "\000\000\000\000\200\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {267, "group6", 4, states_11,
     "\000\000\000\000\000\001\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {268, "group7", 5, states_12,
     "\000\000\000\000\000\002\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {269, "group8", 4, states_13,
     "\000\000\000\000\000\004\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {270, "group9", 4, states_14,
     "\000\000\000\000\000\010\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {271, "group10", 4, states_15,
     "\000\000\000\020\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {272, "group11", 5, states_16,
     "\000\000\000\040\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {273, "group12", 4, states_17,
     "\000\000\000\100\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {274, "group13", 4, states_18,
     "\000\000\000\200\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {275, "group14", 2, states_19,
     "\000\000\000\000\001\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {276, "group15", 5, states_20,
     "\000\000\000\000\002\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {277, "group16", 4, states_21,
     "\000\000\000\000\004\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {278, "imm_exp", 3, states_22,
     "\000\000\000\000\000\000\000\000\000\000\000\100\000\000\000\000\000\000\000\000\000\000"},
    {279, "long_ind_exp", 5, states_23,
     "\000\000\000\000\000\000\000\000\000\000\000\200\000\000\000\000\000\000\000\000\000\000"},
    {280, "jmp_long_ind_exp", 4, states_24,
     "\000\000\000\000\000\000\000\000\000\000\000\200\000\000\000\000\000\000\000\000\000\000"},
    {281, "ind_exp", 8, states_25,
     "\000\000\000\000\000\000\000\000\000\000\000\020\000\000\000\000\000\000\000\000\000\000"},
    {282, "jmp_ind_exp", 6, states_26,
     "\000\000\000\000\000\000\000\000\000\000\000\020\000\000\000\000\000\000\000\000\000\000"},
    {283, "is_exp", 21, states_27,
     "\000\000\000\000\000\000\000\000\000\000\000\000\360\377\000\000\370\001\000\000\000\000"},
    {284, "jmp_is_exp", 20, states_28,
     "\000\000\000\000\000\000\000\000\000\000\000\000\360\377\000\000\370\001\000\000\000\000"},
    {285, "tail_term", 3, states_29,
     "\000\000\000\000\000\000\000\000\000\000\000\000\360\377\000\000\370\001\000\000\000\000"},
    {286, "tail_arith_expr", 3, states_30,
     "\000\000\000\000\000\000\000\000\000\000\000\000\140\373\000\000\370\001\000\000\000\000"},
    {287, "tail_shift_expr", 3, states_31,
     "\000\000\000\000\000\000\000\000\000\000\000\000\140\370\000\000\370\001\000\000\000\000"},
    {288, "tail_and_expr", 3, states_32,
     "\000\000\000\000\000\000\000\000\000\000\000\000\140\340\000\000\370\001\000\000\000\000"},
    {289, "tail_xor_expr", 3, states_33,
     "\000\000\000\000\000\000\000\000\000\000\000\000\040\340\000\000\370\001\000\000\000\000"},
    {290, "tail_or_exp", 3, states_34,
     "\000\000\000\000\000\000\000\000\000\000\000\000\040\300\000\000\370\001\000\000\000\000"},
    {291, "tail_comparison", 3, states_35,
     "\000\000\000\000\000\000\000\000\000\000\000\000\040\200\000\000\370\001\000\000\000\000"},
    {292, "tail_and_cond", 3, states_36,
     "\000\000\000\000\000\000\000\000\000\000\000\000\040\200\000\000\000\000\000\000\000\000"},
    {293, "tail_or_cond", 2, states_37,
     "\000\000\000\000\000\000\000\000\000\000\000\000\000\200\000\000\000\000\000\000\000\000"},
    {294, "x_index", 3, states_38,
     "\000\000\000\000\000\000\000\020\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {295, "y_index", 3, states_39,
     "\000\000\000\000\000\000\000\020\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {296, "s_index", 3, states_40,
     "\000\000\000\000\000\000\000\020\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {297, "xy_index", 3, states_41,
     "\000\000\000\000\000\000\000\020\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {298, "xs_index", 3, states_42,
     "\000\000\000\000\000\000\000\020\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {299, "ys_index", 3, states_43,
     "\000\000\000\000\000\000\000\020\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {300, "xys_index", 3, states_44,
     "\000\000\000\000\000\000\000\020\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {301, "symbol", 5, states_45,
     "\000\004\000\000\000\000\001\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {302, "exp", 2, states_46,
     "\000\004\000\000\000\000\001\000\000\000\000\020\200\033\000\000\220\000\017\000\000\000"},
    {303, "and_cond", 2, states_47,
     "\000\004\000\000\000\000\001\000\000\000\000\020\200\033\000\000\220\000\017\000\000\000"},
    {304, "not_cond", 3, states_48,
     "\000\004\000\000\000\000\001\000\000\000\000\020\200\033\000\000\220\000\017\000\000\000"},
    {305, "comparison", 2, states_49,
     "\000\004\000\000\000\000\001\000\000\000\000\020\200\033\000\000\220\000\016\000\000\000"},
    {306, "comp_op", 2, states_50,
     "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\370\001\000\000\000\000"},
    {307, "or_exp", 2, states_51,
     "\000\004\000\000\000\000\001\000\000\000\000\020\200\033\000\000\220\000\016\000\000\000"},
    {308, "xor_expr", 2, states_52,
     "\000\004\000\000\000\000\001\000\000\000\000\020\200\033\000\000\220\000\016\000\000\000"},
    {309, "and_expr", 2, states_53,
     "\000\004\000\000\000\000\001\000\000\000\000\020\200\033\000\000\220\000\016\000\000\000"},
    {310, "shift_expr", 2, states_54,
     "\000\004\000\000\000\000\001\000\000\000\000\020\200\033\000\000\220\000\016\000\000\000"},
    {311, "arith_expr", 2, states_55,
     "\000\004\000\000\000\000\001\000\000\000\000\020\200\033\000\000\220\000\016\000\000\000"},
    {312, "term", 2, states_56,
     "\000\004\000\000\000\000\001\000\000\000\000\020\200\033\000\000\220\000\016\000\000\000"},
    {313, "factor", 3, states_57,
     "\000\004\000\000\000\000\001\000\000\000\000\020\200\033\000\000\220\000\016\000\000\000"},
    {314, "atom", 4, states_58,
     "\000\004\000\000\000\000\001\000\000\000\000\020\200\000\000\000\000\000\014\000\000\000"},
    {315, "ni_exp", 3, states_59,
     "\000\004\000\000\000\000\001\000\000\000\000\000\200\033\000\000\220\000\017\000\000\000"},
    {316, "ni_and_cond", 3, states_60,
     "\000\004\000\000\000\000\001\000\000\000\000\000\200\033\000\000\220\000\017\000\000\000"},
    {317, "ni_not_cond", 3, states_61,
     "\000\004\000\000\000\000\001\000\000\000\000\000\200\033\000\000\220\000\017\000\000\000"},
    {318, "ni_comparison", 3, states_62,
     "\000\004\000\000\000\000\001\000\000\000\000\000\200\033\000\000\220\000\016\000\000\000"},
    {319, "ni_or_exp", 3, states_63,
     "\000\004\000\000\000\000\001\000\000\000\000\000\200\033\000\000\220\000\016\000\000\000"},
    {320, "ni_xor_expr", 3, states_64,
     "\000\004\000\000\000\000\001\000\000\000\000\000\200\033\000\000\220\000\016\000\000\000"},
    {321, "ni_and_expr", 3, states_65,
     "\000\004\000\000\000\000\001\000\000\000\000\000\200\033\000\000\220\000\016\000\000\000"},
    {322, "ni_shift_expr", 3, states_66,
     "\000\004\000\000\000\000\001\000\000\000\000\000\200\033\000\000\220\000\016\000\000\000"},
    {323, "ni_arith_expr", 3, states_67,
     "\000\004\000\000\000\000\001\000\000\000\000\000\200\033\000\000\220\000\016\000\000\000"},
    {324, "ni_term", 3, states_68,
     "\000\004\000\000\000\000\001\000\000\000\000\000\200\033\000\000\220\000\016\000\000\000"},
    {325, "ni_factor", 3, states_69,
     "\000\004\000\000\000\000\001\000\000\000\000\000\200\033\000\000\220\000\016\000\000\000"},
    {326, "ni_atom", 2, states_70,
     "\000\004\000\000\000\000\001\000\000\000\000\000\200\000\000\000\000\000\014\000\000\000"},
    {327, "pseudo_op", 2, states_71,
     "\000\360\377\004\000\160\074\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {328, "define_byte", 3, states_72,
     "\000\000\004\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {329, "define_word", 3, states_73,
     "\000\000\052\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {330, "define_storage", 3, states_74,
     "\000\000\020\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {331, "align", 3, states_75,
     "\000\020\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {332, "block", 3, states_76,
     "\000\040\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {333, "if_def", 3, states_77,
     "\000\000\000\000\000\140\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {334, "iff", 3, states_78,
     "\000\000\000\000\000\020\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
};
static const label labels[168] = {
    {0, "EMPTY"},
    {256, nullptr},
    {0, nullptr},
    {4, nullptr},
    {257, nullptr},
    {260, nullptr},
    {261, nullptr},
    {327, nullptr},
    {259, nullptr},
    {258, nullptr},
    {76, nullptr},
    {75, nullptr},
    {53, nullptr},
    {54, nullptr},
    {38, nullptr},
    {39, nullptr},
    {40, nullptr},
    {51, nullptr},
    {48, nullptr},
    {50, nullptr},
    {52, nullptr},
    {49, nullptr},
    {46, nullptr},
    {47, nullptr},
    {12, nullptr},
    {9, nullptr},
    {45, nullptr},
    {5, nullptr},
    {22, nullptr},
    {23, nullptr},
    {24, nullptr},
    {25, nullptr},
    {26, nullptr},
    {27, nullptr},
    {28, nullptr},
    {13, nullptr},
    {14, nullptr},
    {15, nullptr},
    {16, nullptr},
    {17, nullptr},
    {18, nullptr},
    {19, nullptr},
    {20, nullptr},
    {21, nullptr},
    {57, nullptr},
    {55, nullptr},
    {56, nullptr},
    {11, nullptr},
    {1, nullptr},
    {8, nullptr},
    {42, nullptr},
    {44, nullptr},
    {41, nullptr},
    {43, nullptr},
    {64, nullptr},
    {58, nullptr},
    {302, nullptr},
    {7, nullptr},
    {6, nullptr},
    {10, nullptr},
    {65, nullptr},
    {262, nullptr},
    {271, nullptr},
    {272, nullptr},
    {273, nullptr},
    {274, nullptr},
    {275, nullptr},
    {276, nullptr},
    {277, nullptr},
    {263, nullptr},
    {264, nullptr},
    {265, nullptr},
    {266, nullptr},
    {267, nullptr},
    {268, nullptr},
    {269, nullptr},
    {270, nullptr},
    {32, nullptr},
    {31, nullptr},
    {30, nullptr},
    {29, nullptr},
    {33, nullptr},
    {278, nullptr},
    {281, nullptr},
    {279, nullptr},
    {315, nullptr},
    {300, nullptr},
    {34, nullptr},
    {294, nullptr},
    {282, nullptr},
    {280, nullptr},
    {295, nullptr},
    {60, nullptr},
    {61, nullptr},
    {59, nullptr},
    {62, nullptr},
    {63, nullptr},
    {296, nullptr},
    {283, nullptr},
    {284, nullptr},
    {77, nullptr},
    {90, nullptr},
    {72, nullptr},
    {69, nullptr},
    {67, nullptr},
    {68, nullptr},
    {70, nullptr},
    {87, nullptr},
    {88, nullptr},
    {86, nullptr},
    {71, nullptr},
    {89, nullptr},
    {306, nullptr},
    {313, nullptr},
    {304, nullptr},
    {310, nullptr},
    {312, nullptr},
    {311, nullptr},
    {309, nullptr},
    {308, nullptr},
    {303, nullptr},
    {307, nullptr},
    {285, nullptr},
    {292, nullptr},
    {288, nullptr},
    {286, nullptr},
    {287, nullptr},
    {289, nullptr},
    {290, nullptr},
    {293, nullptr},
    {291, nullptr},
    {82, nullptr},
    {73, nullptr},
    {83, nullptr},
    {81, nullptr},
    {74, nullptr},
    {84, nullptr},
    {35, nullptr},
    {36, nullptr},
    {37, nullptr},
    {297, nullptr},
    {298, nullptr},
    {299, nullptr},
    {301, nullptr},
    {80, nullptr},
    {85, nullptr},
    {2, nullptr},
    {3, nullptr},
    {305, nullptr},
    {314, nullptr},
    {316, nullptr},
    {317, nullptr},
    {318, nullptr},
    {319, nullptr},
    {320, nullptr},
    {321, nullptr},
    {322, nullptr},
    {323, nullptr},
    {324, nullptr},
    {325, nullptr},
    {326, nullptr},
    {331, nullptr},
    {332, nullptr},
    {328, nullptr},
    {330, nullptr},
    {329, nullptr},
    {333, nullptr},
    {334, nullptr},
};
grammar casmGrammar = {
    79,
    dfas,
    {168, labels},
    256
};
