/* Generated by Parser/pgen */

#include "grammar.h"
static const arc arcs_0_0[9] = {
    {2, 1},
    {3, 1},
    {4, 2},
    {5, 3},
    {6, 2},
    {7, 2},
    {8, 2},
    {9, 2},
    {10, 2},
};
static const arc arcs_0_1[1] = {
    {0, 1},
};
static const arc arcs_0_2[2] = {
    {2, 1},
    {3, 1},
};
static const arc arcs_0_3[8] = {
    {2, 1},
    {3, 1},
    {4, 2},
    {6, 2},
    {7, 2},
    {8, 2},
    {9, 2},
    {10, 2},
};
static state states_0[4] = {
    {9, arcs_0_0},
    {1, arcs_0_1},
    {2, arcs_0_2},
    {8, arcs_0_3},
};
static const arc arcs_1_0[1] = {
    {50, 1},
};
static const arc arcs_1_1[3] = {
    {56, 2},
    {57, 2},
    {0, 1},
};
static const arc arcs_1_2[1] = {
    {0, 2},
};
static state states_1[3] = {
    {1, arcs_1_0},
    {3, arcs_1_1},
    {1, arcs_1_2},
};
static const arc arcs_2_0[2] = {
    {12, 1},
    {28, 1},
};
static const arc arcs_2_1[1] = {
    {58, 2},
};
static const arc arcs_2_2[1] = {
    {0, 2},
};
static state states_2[3] = {
    {2, arcs_2_0},
    {1, arcs_2_1},
    {1, arcs_2_2},
};
static const arc arcs_3_0[2] = {
    {26, 1},
    {51, 2},
};
static const arc arcs_3_1[1] = {
    {0, 1},
};
static const arc arcs_3_2[4] = {
    {59, 1},
    {60, 1},
    {58, 1},
    {0, 2},
};
static state states_3[3] = {
    {2, arcs_3_0},
    {1, arcs_3_1},
    {4, arcs_3_2},
};
static const arc arcs_4_0[3] = {
    {11, 1},
    {25, 2},
    {49, 2},
};
static const arc arcs_4_1[1] = {
    {50, 3},
};
static const arc arcs_4_2[1] = {
    {0, 2},
};
static const arc arcs_4_3[1] = {
    {61, 4},
};
static const arc arcs_4_4[2] = {
    {62, 3},
    {0, 4},
};
static state states_4[5] = {
    {3, arcs_4_0},
    {1, arcs_4_1},
    {1, arcs_4_2},
    {1, arcs_4_3},
    {2, arcs_4_4},
};
static const arc arcs_5_0[1] = {
    {48, 1},
};
static const arc arcs_5_1[1] = {
    {63, 2},
};
static const arc arcs_5_2[1] = {
    {0, 2},
};
static state states_5[3] = {
    {1, arcs_5_0},
    {1, arcs_5_1},
    {1, arcs_5_2},
};
static const arc arcs_6_0[16] = {
    {64, 1},
    {65, 1},
    {66, 1},
    {67, 1},
    {68, 1},
    {69, 1},
    {70, 1},
    {71, 1},
    {72, 1},
    {73, 1},
    {74, 1},
    {75, 1},
    {76, 1},
    {77, 1},
    {78, 1},
    {79, 1},
};
static const arc arcs_6_1[1] = {
    {0, 1},
};
static state states_6[2] = {
    {16, arcs_6_0},
    {1, arcs_6_1},
};
static const arc arcs_7_0[1] = {
    {36, 1},
};
static const arc arcs_7_1[6] = {
    {80, 2},
    {81, 2},
    {82, 2},
    {58, 3},
    {83, 4},
    {84, 4},
};
static const arc arcs_7_2[1] = {
    {58, 3},
};
static const arc arcs_7_3[2] = {
    {85, 4},
    {0, 3},
};
static const arc arcs_7_4[1] = {
    {0, 4},
};
static state states_7[5] = {
    {1, arcs_7_0},
    {6, arcs_7_1},
    {1, arcs_7_2},
    {2, arcs_7_3},
    {1, arcs_7_4},
};
static const arc arcs_8_0[1] = {
    {37, 1},
};
static const arc arcs_8_1[5] = {
    {86, 2},
    {80, 3},
    {82, 3},
    {58, 4},
    {0, 1},
};
static const arc arcs_8_2[1] = {
    {0, 2},
};
static const arc arcs_8_3[1] = {
    {58, 4},
};
static const arc arcs_8_4[2] = {
    {87, 2},
    {0, 4},
};
static state states_8[5] = {
    {1, arcs_8_0},
    {5, arcs_8_1},
    {1, arcs_8_2},
    {1, arcs_8_3},
    {2, arcs_8_4},
};
static const arc arcs_9_0[1] = {
    {38, 1},
};
static const arc arcs_9_1[4] = {
    {80, 2},
    {81, 2},
    {82, 2},
    {58, 3},
};
static const arc arcs_9_2[1] = {
    {58, 3},
};
static const arc arcs_9_3[1] = {
    {0, 3},
};
static state states_9[4] = {
    {1, arcs_9_0},
    {4, arcs_9_1},
    {1, arcs_9_2},
    {1, arcs_9_3},
};
static const arc arcs_10_0[1] = {
    {39, 1},
};
static const arc arcs_10_1[4] = {
    {80, 2},
    {82, 2},
    {58, 3},
    {83, 4},
};
static const arc arcs_10_2[1] = {
    {58, 3},
};
static const arc arcs_10_3[2] = {
    {87, 4},
    {0, 3},
};
static const arc arcs_10_4[1] = {
    {0, 4},
};
static state states_10[5] = {
    {1, arcs_10_0},
    {4, arcs_10_1},
    {1, arcs_10_2},
    {2, arcs_10_3},
    {1, arcs_10_4},
};
static const arc arcs_11_0[1] = {
    {40, 1},
};
static const arc arcs_11_1[4] = {
    {80, 2},
    {82, 2},
    {58, 3},
    {83, 3},
};
static const arc arcs_11_2[1] = {
    {58, 3},
};
static const arc arcs_11_3[1] = {
    {0, 3},
};
static state states_11[4] = {
    {1, arcs_11_0},
    {4, arcs_11_1},
    {1, arcs_11_2},
    {1, arcs_11_3},
};
static const arc arcs_12_0[1] = {
    {41, 1},
};
static const arc arcs_12_1[1] = {
    {83, 2},
};
static const arc arcs_12_2[1] = {
    {0, 2},
};
static state states_12[3] = {
    {1, arcs_12_0},
    {1, arcs_12_1},
    {1, arcs_12_2},
};
static const arc arcs_13_0[1] = {
    {42, 1},
};
static const arc arcs_13_1[1] = {
    {58, 2},
};
static const arc arcs_13_2[1] = {
    {62, 3},
};
static const arc arcs_13_3[1] = {
    {58, 4},
};
static const arc arcs_13_4[1] = {
    {0, 4},
};
static state states_13[5] = {
    {1, arcs_13_0},
    {1, arcs_13_1},
    {1, arcs_13_2},
    {1, arcs_13_3},
    {1, arcs_13_4},
};
static const arc arcs_14_0[1] = {
    {43, 1},
};
static const arc arcs_14_1[3] = {
    {81, 2},
    {58, 3},
    {88, 3},
};
static const arc arcs_14_2[1] = {
    {58, 3},
};
static const arc arcs_14_3[1] = {
    {0, 3},
};
static state states_14[4] = {
    {1, arcs_14_0},
    {3, arcs_14_1},
    {1, arcs_14_2},
    {1, arcs_14_3},
};
static const arc arcs_15_0[1] = {
    {44, 1},
};
static const arc arcs_15_1[3] = {
    {81, 2},
    {58, 3},
    {88, 3},
};
static const arc arcs_15_2[1] = {
    {58, 3},
};
static const arc arcs_15_3[1] = {
    {0, 3},
};
static state states_15[4] = {
    {1, arcs_15_0},
    {3, arcs_15_1},
    {1, arcs_15_2},
    {1, arcs_15_3},
};
static const arc arcs_16_0[1] = {
    {29, 1},
};
static const arc arcs_16_1[2] = {
    {81, 2},
    {58, 3},
};
static const arc arcs_16_2[1] = {
    {58, 3},
};
static const arc arcs_16_3[1] = {
    {0, 3},
};
static state states_16[4] = {
    {1, arcs_16_0},
    {2, arcs_16_1},
    {1, arcs_16_2},
    {1, arcs_16_3},
};
static const arc arcs_17_0[1] = {
    {30, 1},
};
static const arc arcs_17_1[4] = {
    {80, 2},
    {82, 2},
    {58, 3},
    {83, 4},
};
static const arc arcs_17_2[1] = {
    {58, 3},
};
static const arc arcs_17_3[2] = {
    {89, 4},
    {0, 3},
};
static const arc arcs_17_4[1] = {
    {0, 4},
};
static state states_17[5] = {
    {1, arcs_17_0},
    {4, arcs_17_1},
    {1, arcs_17_2},
    {2, arcs_17_3},
    {1, arcs_17_4},
};
static const arc arcs_18_0[1] = {
    {31, 1},
};
static const arc arcs_18_1[3] = {
    {80, 2},
    {82, 2},
    {58, 3},
};
static const arc arcs_18_2[1] = {
    {58, 3},
};
static const arc arcs_18_3[2] = {
    {89, 4},
    {0, 3},
};
static const arc arcs_18_4[1] = {
    {0, 4},
};
static state states_18[5] = {
    {1, arcs_18_0},
    {3, arcs_18_1},
    {1, arcs_18_2},
    {2, arcs_18_3},
    {1, arcs_18_4},
};
static const arc arcs_19_0[1] = {
    {32, 1},
};
static const arc arcs_19_1[3] = {
    {80, 2},
    {82, 2},
    {58, 3},
};
static const arc arcs_19_2[1] = {
    {58, 3},
};
static const arc arcs_19_3[2] = {
    {87, 4},
    {0, 3},
};
static const arc arcs_19_4[1] = {
    {0, 4},
};
static state states_19[5] = {
    {1, arcs_19_0},
    {3, arcs_19_1},
    {1, arcs_19_2},
    {2, arcs_19_3},
    {1, arcs_19_4},
};
static const arc arcs_20_0[1] = {
    {33, 1},
};
static const arc arcs_20_1[1] = {
    {0, 1},
};
static state states_20[2] = {
    {1, arcs_20_0},
    {1, arcs_20_1},
};
static const arc arcs_21_0[1] = {
    {34, 1},
};
static const arc arcs_21_1[1] = {
    {58, 2},
};
static const arc arcs_21_2[1] = {
    {0, 2},
};
static state states_21[3] = {
    {1, arcs_21_0},
    {1, arcs_21_1},
    {1, arcs_21_2},
};
static const arc arcs_22_0[1] = {
    {35, 1},
};
static const arc arcs_22_1[3] = {
    {90, 2},
    {58, 3},
    {0, 1},
};
static const arc arcs_22_2[1] = {
    {58, 3},
};
static const arc arcs_22_3[1] = {
    {0, 3},
};
static state states_22[4] = {
    {1, arcs_22_0},
    {3, arcs_22_1},
    {1, arcs_22_2},
    {1, arcs_22_3},
};
static const arc arcs_23_0[3] = {
    {90, 1},
    {91, 2},
    {92, 2},
};
static const arc arcs_23_1[1] = {
    {58, 3},
};
static const arc arcs_23_2[1] = {
    {90, 1},
};
static const arc arcs_23_3[1] = {
    {0, 3},
};
static state states_23[4] = {
    {3, arcs_23_0},
    {1, arcs_23_1},
    {1, arcs_23_2},
    {1, arcs_23_3},
};
static const arc arcs_24_0[1] = {
    {93, 1},
};
static const arc arcs_24_1[1] = {
    {58, 2},
};
static const arc arcs_24_2[1] = {
    {94, 3},
};
static const arc arcs_24_3[2] = {
    {89, 4},
    {0, 3},
};
static const arc arcs_24_4[1] = {
    {0, 4},
};
static state states_24[5] = {
    {1, arcs_24_0},
    {1, arcs_24_1},
    {1, arcs_24_2},
    {2, arcs_24_3},
    {1, arcs_24_4},
};
static const arc arcs_25_0[1] = {
    {93, 1},
};
static const arc arcs_25_1[1] = {
    {58, 2},
};
static const arc arcs_25_2[1] = {
    {94, 3},
};
static const arc arcs_25_3[1] = {
    {0, 3},
};
static state states_25[4] = {
    {1, arcs_25_0},
    {1, arcs_25_1},
    {1, arcs_25_2},
    {1, arcs_25_3},
};
static const arc arcs_26_0[1] = {
    {62, 1},
};
static const arc arcs_26_1[1] = {
    {95, 2},
};
static const arc arcs_26_2[1] = {
    {0, 2},
};
static state states_26[3] = {
    {1, arcs_26_0},
    {1, arcs_26_1},
    {1, arcs_26_2},
};
static const arc arcs_27_0[1] = {
    {62, 1},
};
static const arc arcs_27_1[1] = {
    {96, 2},
};
static const arc arcs_27_2[1] = {
    {0, 2},
};
static state states_27[3] = {
    {1, arcs_27_0},
    {1, arcs_27_1},
    {1, arcs_27_2},
};
static const arc arcs_28_0[1] = {
    {62, 1},
};
static const arc arcs_28_1[1] = {
    {98, 2},
};
static const arc arcs_28_2[1] = {
    {0, 2},
};
static state states_28[3] = {
    {1, arcs_28_0},
    {1, arcs_28_1},
    {1, arcs_28_2},
};
static const arc arcs_29_0[1] = {
    {62, 1},
};
static const arc arcs_29_1[2] = {
    {95, 2},
    {96, 2},
};
static const arc arcs_29_2[1] = {
    {0, 2},
};
static state states_29[3] = {
    {1, arcs_29_0},
    {2, arcs_29_1},
    {1, arcs_29_2},
};
static const arc arcs_30_0[1] = {
    {62, 1},
};
static const arc arcs_30_1[2] = {
    {98, 2},
    {95, 2},
};
static const arc arcs_30_2[1] = {
    {0, 2},
};
static state states_30[3] = {
    {1, arcs_30_0},
    {2, arcs_30_1},
    {1, arcs_30_2},
};
static const arc arcs_31_0[1] = {
    {62, 1},
};
static const arc arcs_31_1[2] = {
    {98, 2},
    {96, 2},
};
static const arc arcs_31_2[1] = {
    {0, 2},
};
static state states_31[3] = {
    {1, arcs_31_0},
    {2, arcs_31_1},
    {1, arcs_31_2},
};
static const arc arcs_32_0[1] = {
    {62, 1},
};
static const arc arcs_32_1[3] = {
    {98, 2},
    {95, 2},
    {96, 2},
};
static const arc arcs_32_2[1] = {
    {0, 2},
};
static state states_32[3] = {
    {1, arcs_32_0},
    {3, arcs_32_1},
    {1, arcs_32_2},
};
static const arc arcs_33_0[2] = {
    {11, 1},
    {50, 2},
};
static const arc arcs_33_1[1] = {
    {50, 3},
};
static const arc arcs_33_2[4] = {
    {103, 3},
    {11, 4},
    {56, 3},
    {0, 2},
};
static const arc arcs_33_3[1] = {
    {0, 3},
};
static const arc arcs_33_4[2] = {
    {50, 3},
    {0, 4},
};
static state states_33[5] = {
    {2, arcs_33_0},
    {1, arcs_33_1},
    {4, arcs_33_2},
    {1, arcs_33_3},
    {2, arcs_33_4},
};
static const arc arcs_34_0[1] = {
    {104, 1},
};
static const arc arcs_34_1[2] = {
    {105, 0},
    {0, 1},
};
static state states_34[2] = {
    {1, arcs_34_0},
    {2, arcs_34_1},
};
static const arc arcs_35_0[1] = {
    {117, 1},
};
static const arc arcs_35_1[2] = {
    {118, 0},
    {0, 1},
};
static state states_35[2] = {
    {1, arcs_35_0},
    {2, arcs_35_1},
};
static const arc arcs_36_0[2] = {
    {106, 1},
    {119, 2},
};
static const arc arcs_36_1[1] = {
    {117, 2},
};
static const arc arcs_36_2[1] = {
    {0, 2},
};
static state states_36[3] = {
    {2, arcs_36_0},
    {1, arcs_36_1},
    {1, arcs_36_2},
};
static const arc arcs_37_0[1] = {
    {120, 1},
};
static const arc arcs_37_1[2] = {
    {121, 0},
    {0, 1},
};
static state states_37[2] = {
    {1, arcs_37_0},
    {2, arcs_37_1},
};
static const arc arcs_38_0[6] = {
    {122, 1},
    {111, 1},
    {123, 1},
    {124, 1},
    {113, 1},
    {125, 1},
};
static const arc arcs_38_1[1] = {
    {0, 1},
};
static state states_38[2] = {
    {6, arcs_38_0},
    {1, arcs_38_1},
};
static const arc arcs_39_0[1] = {
    {126, 1},
};
static const arc arcs_39_1[2] = {
    {127, 0},
    {0, 1},
};
static state states_39[2] = {
    {1, arcs_39_0},
    {2, arcs_39_1},
};
static const arc arcs_40_0[1] = {
    {128, 1},
};
static const arc arcs_40_1[2] = {
    {129, 0},
    {0, 1},
};
static state states_40[2] = {
    {1, arcs_40_0},
    {2, arcs_40_1},
};
static const arc arcs_41_0[1] = {
    {130, 1},
};
static const arc arcs_41_1[2] = {
    {103, 0},
    {0, 1},
};
static state states_41[2] = {
    {1, arcs_41_0},
    {2, arcs_41_1},
};
static const arc arcs_42_0[1] = {
    {131, 1},
};
static const arc arcs_42_1[3] = {
    {112, 0},
    {114, 0},
    {0, 1},
};
static state states_42[2] = {
    {1, arcs_42_0},
    {3, arcs_42_1},
};
static const arc arcs_43_0[1] = {
    {132, 1},
};
static const arc arcs_43_1[3] = {
    {109, 0},
    {110, 0},
    {0, 1},
};
static state states_43[2] = {
    {1, arcs_43_0},
    {3, arcs_43_1},
};
static const arc arcs_44_0[1] = {
    {133, 1},
};
static const arc arcs_44_1[4] = {
    {134, 0},
    {108, 0},
    {135, 0},
    {0, 1},
};
static state states_44[2] = {
    {1, arcs_44_0},
    {4, arcs_44_1},
};
static const arc arcs_45_0[8] = {
    {109, 1},
    {110, 1},
    {111, 1},
    {112, 1},
    {113, 1},
    {114, 1},
    {115, 1},
    {136, 2},
};
static const arc arcs_45_1[1] = {
    {133, 2},
};
static const arc arcs_45_2[1] = {
    {0, 2},
};
static state states_45[3] = {
    {8, arcs_45_0},
    {1, arcs_45_1},
    {1, arcs_45_2},
};
static const arc arcs_46_0[5] = {
    {107, 1},
    {108, 2},
    {116, 2},
    {63, 2},
    {102, 2},
};
static const arc arcs_46_1[1] = {
    {58, 3},
};
static const arc arcs_46_2[1] = {
    {0, 2},
};
static const arc arcs_46_3[2] = {
    {137, 2},
    {100, 4},
};
static const arc arcs_46_4[1] = {
    {137, 2},
};
static state states_46[5] = {
    {5, arcs_46_0},
    {1, arcs_46_1},
    {1, arcs_46_2},
    {2, arcs_46_3},
    {1, arcs_46_4},
};
static const arc arcs_47_0[17] = {
    {15, 1},
    {16, 1},
    {17, 1},
    {23, 1},
    {24, 1},
    {27, 1},
    {52, 1},
    {53, 1},
    {54, 1},
    {55, 1},
    {138, 1},
    {139, 1},
    {140, 1},
    {141, 1},
    {142, 1},
    {143, 1},
    {144, 1},
};
static const arc arcs_47_1[1] = {
    {0, 1},
};
static state states_47[2] = {
    {17, arcs_47_0},
    {1, arcs_47_1},
};
static const arc arcs_48_0[1] = {
    {19, 1},
};
static const arc arcs_48_1[1] = {
    {58, 2},
};
static const arc arcs_48_2[2] = {
    {62, 1},
    {0, 2},
};
static state states_48[3] = {
    {1, arcs_48_0},
    {1, arcs_48_1},
    {2, arcs_48_2},
};
static const arc arcs_49_0[3] = {
    {18, 1},
    {20, 1},
    {22, 1},
};
static const arc arcs_49_1[1] = {
    {58, 2},
};
static const arc arcs_49_2[2] = {
    {62, 1},
    {0, 2},
};
static state states_49[3] = {
    {3, arcs_49_0},
    {1, arcs_49_1},
    {2, arcs_49_2},
};
static const arc arcs_50_0[1] = {
    {21, 1},
};
static const arc arcs_50_1[1] = {
    {58, 2},
};
static const arc arcs_50_2[1] = {
    {0, 2},
};
static state states_50[3] = {
    {1, arcs_50_0},
    {1, arcs_50_1},
    {1, arcs_50_2},
};
static const arc arcs_51_0[1] = {
    {13, 1},
};
static const arc arcs_51_1[2] = {
    {59, 2},
    {60, 2},
};
static const arc arcs_51_2[1] = {
    {0, 2},
};
static state states_51[3] = {
    {1, arcs_51_0},
    {2, arcs_51_1},
    {1, arcs_51_2},
};
static const arc arcs_52_0[1] = {
    {14, 1},
};
static const arc arcs_52_1[1] = {
    {58, 2},
};
static const arc arcs_52_2[1] = {
    {0, 2},
};
static state states_52[3] = {
    {1, arcs_52_0},
    {1, arcs_52_1},
    {1, arcs_52_2},
};
static const arc arcs_53_0[2] = {
    {46, 1},
    {47, 1},
};
static const arc arcs_53_1[1] = {
    {58, 2},
};
static const arc arcs_53_2[1] = {
    {0, 2},
};
static state states_53[3] = {
    {2, arcs_53_0},
    {1, arcs_53_1},
    {1, arcs_53_2},
};
static const arc arcs_54_0[1] = {
    {45, 1},
};
static const arc arcs_54_1[1] = {
    {58, 2},
};
static const arc arcs_54_2[1] = {
    {0, 2},
};
static state states_54[3] = {
    {1, arcs_54_0},
    {1, arcs_54_1},
    {1, arcs_54_2},
};
static const dfa dfas[55] = {
    {256, "line", 4, states_0,
     "\014\370\377\377\377\377\377\000\000\000\000\000\000\000\000\000\000\000\000"},
    {257, "label", 3, states_1,
     "\000\000\000\000\000\000\004\000\000\000\000\000\000\000\000\000\000\000\000"},
    {258, "variable", 3, states_2,
     "\000\020\000\020\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {259, "region", 3, states_3,
     "\000\000\000\004\000\000\010\000\000\000\000\000\000\000\000\000\000\000\000"},
    {260, "macro", 5, states_4,
     "\000\010\000\002\000\000\002\000\000\000\000\000\000\000\000\000\000\000\000"},
    {261, "include", 3, states_5,
     "\000\000\000\000\000\000\001\000\000\000\000\000\000\000\000\000\000\000\000"},
    {262, "op_code", 2, states_6,
     "\000\000\000\340\377\037\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {263, "group1", 5, states_7,
     "\000\000\000\000\020\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {264, "group2", 5, states_8,
     "\000\000\000\000\040\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {265, "group3", 4, states_9,
     "\000\000\000\000\100\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {266, "group4", 5, states_10,
     "\000\000\000\000\200\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {267, "group5", 4, states_11,
     "\000\000\000\000\000\001\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {268, "group6", 3, states_12,
     "\000\000\000\000\000\002\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {269, "group7", 5, states_13,
     "\000\000\000\000\000\004\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {270, "group8", 4, states_14,
     "\000\000\000\000\000\010\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {271, "group9", 4, states_15,
     "\000\000\000\000\000\020\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {272, "group10", 4, states_16,
     "\000\000\000\040\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {273, "group11", 5, states_17,
     "\000\000\000\100\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {274, "group12", 5, states_18,
     "\000\000\000\200\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {275, "group13", 5, states_19,
     "\000\000\000\000\001\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {276, "group14", 2, states_20,
     "\000\000\000\000\002\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {277, "group15", 3, states_21,
     "\000\000\000\000\004\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {278, "group16", 4, states_22,
     "\000\000\000\000\010\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {279, "imm_exp", 4, states_23,
     "\000\000\000\000\000\000\000\000\000\000\000\034\000\000\000\000\000\000\000"},
    {280, "long_ind_exp", 5, states_24,
     "\000\000\000\000\000\000\000\000\000\000\000\040\000\000\000\000\000\000\000"},
    {281, "jmp_long_ind_exp", 4, states_25,
     "\000\000\000\000\000\000\000\000\000\000\000\040\000\000\000\000\000\000\000"},
    {282, "x_index", 3, states_26,
     "\000\000\000\000\000\000\000\100\000\000\000\000\000\000\000\000\000\000\000"},
    {283, "y_index", 3, states_27,
     "\000\000\000\000\000\000\000\100\000\000\000\000\000\000\000\000\000\000\000"},
    {284, "s_index", 3, states_28,
     "\000\000\000\000\000\000\000\100\000\000\000\000\000\000\000\000\000\000\000"},
    {285, "xy_index", 3, states_29,
     "\000\000\000\000\000\000\000\100\000\000\000\000\000\000\000\000\000\000\000"},
    {286, "xs_index", 3, states_30,
     "\000\000\000\000\000\000\000\100\000\000\000\000\000\000\000\000\000\000\000"},
    {287, "ys_index", 3, states_31,
     "\000\000\000\000\000\000\000\100\000\000\000\000\000\000\000\000\000\000\000"},
    {288, "xys_index", 3, states_32,
     "\000\000\000\000\000\000\000\100\000\000\000\000\000\000\000\000\000\000\000"},
    {289, "symbol", 5, states_33,
     "\000\010\000\000\000\000\004\000\000\000\000\000\000\000\000\000\000\000\000"},
    {290, "exp", 2, states_34,
     "\000\010\000\000\000\000\004\200\000\000\000\000\000\374\037\000\000\000\000"},
    {291, "and_cond", 2, states_35,
     "\000\010\000\000\000\000\004\200\000\000\000\000\000\374\037\000\000\000\000"},
    {292, "not_cond", 3, states_36,
     "\000\010\000\000\000\000\004\200\000\000\000\000\000\374\037\000\000\000\000"},
    {293, "comparison", 2, states_37,
     "\000\010\000\000\000\000\004\200\000\000\000\000\000\370\037\000\000\000\000"},
    {294, "comp_op", 2, states_38,
     "\000\000\000\000\000\000\000\000\000\000\000\000\000\200\002\074\000\000\000"},
    {295, "or_exp", 2, states_39,
     "\000\010\000\000\000\000\004\200\000\000\000\000\000\370\037\000\000\000\000"},
    {296, "xor_expr", 2, states_40,
     "\000\010\000\000\000\000\004\200\000\000\000\000\000\370\037\000\000\000\000"},
    {297, "and_expr", 2, states_41,
     "\000\010\000\000\000\000\004\200\000\000\000\000\000\370\037\000\000\000\000"},
    {298, "shift_expr", 2, states_42,
     "\000\010\000\000\000\000\004\200\000\000\000\000\000\370\037\000\000\000\000"},
    {299, "arith_expr", 2, states_43,
     "\000\010\000\000\000\000\004\200\000\000\000\000\000\370\037\000\000\000\000"},
    {300, "term", 2, states_44,
     "\000\010\000\000\000\000\004\200\000\000\000\000\000\370\037\000\000\000\000"},
    {301, "factor", 3, states_45,
     "\000\010\000\000\000\000\004\200\000\000\000\000\000\370\037\000\000\000\000"},
    {302, "atom", 5, states_46,
     "\000\010\000\000\000\000\004\200\000\000\000\000\000\030\020\000\000\000\000"},
    {303, "pseudo_op", 2, states_47,
     "\000\340\377\011\000\340\360\000\000\000\000\000\000\000\000\000\000\000\000"},
    {304, "define_byte", 3, states_48,
     "\000\000\010\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {305, "define_word", 3, states_49,
     "\000\000\124\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {306, "define_storage", 3, states_50,
     "\000\000\040\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {307, "align", 3, states_51,
     "\000\040\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {308, "block", 3, states_52,
     "\000\100\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {309, "if_def", 3, states_53,
     "\000\000\000\000\000\300\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {310, "iff", 3, states_54,
     "\000\000\000\000\000\040\000\000\000\000\000\000\000\000\000\000\000\000\000"},
};
static const label labels[145] = {
    {0, "EMPTY"},
    {256, nullptr},
    {0, nullptr},
    {4, nullptr},
    {261, nullptr},
    {257, nullptr},
    {260, nullptr},
    {262, nullptr},
    {303, nullptr},
    {259, nullptr},
    {258, nullptr},
    {77, nullptr},
    {76, nullptr},
    {54, nullptr},
    {55, nullptr},
    {39, nullptr},
    {40, nullptr},
    {41, nullptr},
    {52, nullptr},
    {49, nullptr},
    {51, nullptr},
    {53, nullptr},
    {50, nullptr},
    {47, nullptr},
    {48, nullptr},
    {12, nullptr},
    {9, nullptr},
    {46, nullptr},
    {5, nullptr},
    {23, nullptr},
    {24, nullptr},
    {25, nullptr},
    {26, nullptr},
    {27, nullptr},
    {28, nullptr},
    {29, nullptr},
    {14, nullptr},
    {15, nullptr},
    {16, nullptr},
    {17, nullptr},
    {18, nullptr},
    {19, nullptr},
    {20, nullptr},
    {21, nullptr},
    {22, nullptr},
    {58, nullptr},
    {56, nullptr},
    {57, nullptr},
    {13, nullptr},
    {11, nullptr},
    {1, nullptr},
    {8, nullptr},
    {43, nullptr},
    {45, nullptr},
    {42, nullptr},
    {44, nullptr},
    {65, nullptr},
    {59, nullptr},
    {290, nullptr},
    {7, nullptr},
    {6, nullptr},
    {10, nullptr},
    {66, nullptr},
    {3, nullptr},
    {263, nullptr},
    {272, nullptr},
    {273, nullptr},
    {274, nullptr},
    {275, nullptr},
    {276, nullptr},
    {277, nullptr},
    {278, nullptr},
    {264, nullptr},
    {265, nullptr},
    {266, nullptr},
    {267, nullptr},
    {268, nullptr},
    {269, nullptr},
    {270, nullptr},
    {271, nullptr},
    {33, nullptr},
    {32, nullptr},
    {34, nullptr},
    {279, nullptr},
    {280, nullptr},
    {288, nullptr},
    {35, nullptr},
    {282, nullptr},
    {281, nullptr},
    {283, nullptr},
    {60, nullptr},
    {31, nullptr},
    {30, nullptr},
    {63, nullptr},
    {64, nullptr},
    {36, nullptr},
    {37, nullptr},
    {284, nullptr},
    {38, nullptr},
    {285, nullptr},
    {286, nullptr},
    {287, nullptr},
    {289, nullptr},
    {73, nullptr},
    {291, nullptr},
    {90, nullptr},
    {81, nullptr},
    {61, nullptr},
    {70, nullptr},
    {68, nullptr},
    {69, nullptr},
    {74, nullptr},
    {88, nullptr},
    {75, nullptr},
    {89, nullptr},
    {86, nullptr},
    {2, nullptr},
    {292, nullptr},
    {91, nullptr},
    {293, nullptr},
    {295, nullptr},
    {294, nullptr},
    {83, nullptr},
    {84, nullptr},
    {82, nullptr},
    {85, nullptr},
    {296, nullptr},
    {72, nullptr},
    {297, nullptr},
    {87, nullptr},
    {298, nullptr},
    {299, nullptr},
    {300, nullptr},
    {301, nullptr},
    {78, nullptr},
    {71, nullptr},
    {302, nullptr},
    {62, nullptr},
    {307, nullptr},
    {308, nullptr},
    {304, nullptr},
    {306, nullptr},
    {305, nullptr},
    {309, nullptr},
    {310, nullptr},
};
grammar casmGrammar = {
    55,
    dfas,
    {145, labels},
    256
};
