/* Auto-generated by Parser/pgen */

/* Token types */
#ifndef TOKEN_H
#define TOKEN_H

#undef TILDE   /* Prevent clash of our definition with system macro. Ex AIX, ioctl.h */

const int ENDMARKER       = 0;
const int NAME            = 1;
const int NUMBER          = 2;
const int STRING          = 3;
const int NEWLINE         = 4;
const int EQU             = 5;
const int BYTE            = 6;
const int WORD            = 7;
const int DWORD           = 8;
const int PARA            = 9;
const int PAGE            = 10;
const int ABS             = 11;
const int STORAGE         = 12;
const int SEGMENT         = 13;
const int ENDS            = 14;
const int ARG             = 15;
const int MACRO           = 16;
const int ENDM            = 17;
const int INCLUDE         = 18;
const int IMPORT          = 19;
const int EXPORT          = 20;
const int GROUP1_INST     = 21;
const int GROUP2_INST     = 22;
const int GROUP3_INST     = 23;
const int GROUP4_INST     = 24;
const int GROUP5_INST     = 25;
const int GROUP6_INST     = 26;
const int GROUP7_INST     = 27;
const int GROUP8_INST     = 28;
const int GROUP9_INST     = 29;
const int GROUP10_INST    = 30;
const int GROUP11_INST    = 31;
const int GROUP12_INST    = 32;
const int GROUP13_INST    = 33;
const int GROUP14_INST    = 34;
const int GROUP15_INST    = 35;
const int GROUP16_INST    = 36;
const int WIDE            = 37;
const int SHORT           = 38;
const int LONG            = 39;
const int DP              = 40;
const int ZP              = 41;
const int AREG            = 42;
const int XREG            = 43;
const int YREG            = 44;
const int SREG            = 45;
const int CPU6502         = 46;
const int CPU65C02        = 47;
const int CPU65C816       = 48;
const int WIDEA           = 49;
const int SHORTA          = 50;
const int WIDEXY          = 51;
const int SHORTXY         = 52;
const int END_BLOCK       = 53;
const int ELSE            = 54;
const int ENDIF           = 55;
const int DB              = 56;
const int DW              = 57;
const int DBW             = 58;
const int DA              = 59;
const int DS              = 60;
const int ALIGN           = 61;
const int BLOCK           = 62;
const int IFDEF           = 63;
const int IFNDEF          = 64;
const int IF              = 65;
const int QUESTION        = 66;
const int HASH            = 67;
const int LPAR            = 68;
const int RPAR            = 69;
const int LSQB            = 70;
const int RSQB            = 71;
const int COLON           = 72;
const int COMMA           = 73;
const int SEMI            = 74;
const int PLUS            = 75;
const int MINUS           = 76;
const int STAR            = 77;
const int SLASH           = 78;
const int VBAR            = 79;
const int AMPER           = 80;
const int LESS            = 81;
const int GREATER         = 82;
const int EQUAL           = 83;
const int DOT             = 84;
const int PERCENT         = 85;
const int LBRACE          = 86;
const int RBRACE          = 87;
const int EXCLAMATION     = 88;
const int EQEQUAL         = 89;
const int NOTEQUAL        = 90;
const int LESSEQUAL       = 91;
const int GREATEREQUAL    = 92;
const int TILDE           = 93;
const int CIRCUMFLEX      = 94;
const int LEFTSHIFT       = 95;
const int RIGHTSHIFT      = 96;
const int DOUBLEVBAR      = 97;
const int DUUBLEAMPER     = 98;
const int OP              = 99;
const int ERRORTOKEN      = 100;
const int N_TOKENS        = 104;
const int NT_OFFSET       = 256;

/* Special definitions for cooperation with parser */

inline bool ISTERMINAL(int x) { return x < NT_OFFSET; }
inline bool ISNONTERMINAL(int x) {return x >= NT_OFFSET; }
inline bool ISEOF(int x) { return x == ENDMARKER; }


extern const char * const casmTokenNames[]; /* Token names */
int oneChar(int);
int twoChars(int, int);
int threeChars(int, int, int);

#endif /* !TOKEN_H */
