/* Auto-generated by Parser/pgen */

/* Token types */
#ifndef TOKEN_H
#define TOKEN_H

#undef TILDE   /* Prevent clash of our definition with system macro. Ex AIX, ioctl.h */

const int ENDMARKER       = 0;
const int NAME            = 1;
const int NUMBER          = 2;
const int STRING          = 3;
const int NEWLINE         = 4;
const int EQU             = 5;
const int PARA            = 6;
const int PAGE            = 7;
const int SEGMENT         = 8;
const int ENDS            = 9;
const int ARG             = 10;
const int MACRO           = 11;
const int ENDM            = 12;
const int INCLUDE         = 13;
const int GROUP1_INST     = 14;
const int GROUP2_INST     = 15;
const int GROUP3_INST     = 16;
const int GROUP4_INST     = 17;
const int GROUP5_INST     = 18;
const int GROUP6_INST     = 19;
const int GROUP7_INST     = 20;
const int GROUP8_INST     = 21;
const int GROUP9_INST     = 22;
const int GROUP10_INST    = 23;
const int GROUP11_INST    = 24;
const int GROUP12_INST    = 25;
const int GROUP13_INST    = 26;
const int GROUP14_INST    = 27;
const int GROUP15_INST    = 28;
const int GROUP16_INST    = 29;
const int WIDE            = 30;
const int SHORT           = 31;
const int LONG            = 32;
const int DP              = 33;
const int ZP              = 34;
const int AREG            = 35;
const int XREG            = 36;
const int YREG            = 37;
const int SREG            = 38;
const int CPU6502         = 39;
const int CPU65C02        = 40;
const int CPU65C816       = 41;
const int WIDEA           = 42;
const int SHORTA          = 43;
const int WIDEXY          = 44;
const int SHORTXY         = 45;
const int END_BLOCK       = 46;
const int ELSE            = 47;
const int ENDIF           = 48;
const int DB              = 49;
const int DW              = 50;
const int DBW             = 51;
const int DA              = 52;
const int DS              = 53;
const int ALIGN           = 54;
const int BLOCK           = 55;
const int IFDEF           = 56;
const int IFNDEF          = 57;
const int IF              = 58;
const int QUESTION        = 59;
const int HASH            = 60;
const int LPAR            = 61;
const int RPAR            = 62;
const int LSQB            = 63;
const int RSQB            = 64;
const int COLON           = 65;
const int COMMA           = 66;
const int SEMI            = 67;
const int PLUS            = 68;
const int MINUS           = 69;
const int STAR            = 70;
const int SLASH           = 71;
const int VBAR            = 72;
const int AMPER           = 73;
const int LESS            = 74;
const int GREATER         = 75;
const int EQUAL           = 76;
const int DOT             = 77;
const int PERCENT         = 78;
const int LBRACE          = 79;
const int RBRACE          = 80;
const int EXCLAMATION     = 81;
const int EQEQUAL         = 82;
const int NOTEQUAL        = 83;
const int LESSEQUAL       = 84;
const int GREATEREQUAL    = 85;
const int TILDE           = 86;
const int CIRCUMFLEX      = 87;
const int LEFTSHIFT       = 88;
const int RIGHTSHIFT      = 89;
const int DOUBLEVBAR      = 90;
const int DUUBLEAMPER     = 91;
const int OP              = 92;
const int ERRORTOKEN      = 93;
const int N_TOKENS        = 97;
const int NT_OFFSET       = 256;

/* Special definitions for cooperation with parser */

inline bool ISTERMINAL(int x) { return x < NT_OFFSET; }
inline bool ISNONTERMINAL(int x) {return x >= NT_OFFSET; }
inline bool ISEOF(int x) { return x == ENDMARKER; }


extern const char * const casmTokenNames[]; /* Token names */
int oneChar(int);
int twoChars(int, int);
int threeChars(int, int, int);

#endif /* !TOKEN_H */
